#!/usr/bin/env python
# coding: utf8
from __future__ import unicode_literals, print_function

TRAIN_DATA_EDITORA_1E = [
("ATICA",{"entities":[(0,5,'EDITORA')]}),
("ALTA BOOKS",{"entities":[(0,10,'EDITORA')]}),
("S.E. AGORA",{"entities":[(0,10,'EDITORA')]}),
("CENGAGE LEARNING",{"entities":[(0,16,'EDITORA')]}),
("ARCA GRAFICA",{"entities":[(0,12,'EDITORA')]}),
("SEPAL",{"entities":[(0,5,'EDITORA')]}),
("S.E. W",{"entities":[(0,6,'EDITORA')]}),
("ABC",{"entities":[(0,3,'EDITORA')]}),
("ABBA",{"entities":[(0,4,'EDITORA')]}),
("ABRIL CULTURAL",{"entities":[(0,14,'EDITORA')]}),
("AB",{"entities":[(0,2,'EDITORA')]}),
("ABRAMUNDO",{"entities":[(0,9,'EDITORA')]}),
("S.E. ATITUDE BY PEARSON",{"entities":[(0,23,'EDITORA')]}),
("ABRIL JOVEM",{"entities":[(0,11,'EDITORA')]}),
("ACCESS EDITORA",{"entities":[(0,14,'EDITORA')]}),
("SEFRAN",{"entities":[(0,6,'EDITORA')]}),
("ARCO LIBROS",{"entities":[(0,11,'EDITORA')]}),
("S.E. INTERATIVO",{"entities":[(0,15,'EDITORA')]}),
("EDITORA ACSI",{"entities":[(0,12,'EDITORA')]}),
("S.E. CANDIDO CALAZANS",{"entities":[(0,21,'EDITORA')]}),
("PASSARADA",{"entities":[(0,9,'EDITORA')]}),
("S.E. DOCTUM",{"entities":[(0,11,'EDITORA')]}),
("AM EDICOES",{"entities":[(0,10,'EDITORA')]}),
("ADUANEIRAS",{"entities":[(0,10,'EDITORA')]}),
("S.E. CASE",{"entities":[(0,9,'EDITORA')]}),
("MENS'ANA",{"entities":[(0,8,'EDITORA')]}),
("AEROPLANO",{"entities":[(0,9,'EDITORA')]}),
("ALFAGUARA",{"entities":[(0,9,'EDITORA')]}),
("SEI",{"entities":[(0,3,'EDITORA')]}),
("S.E. FTD",{"entities":[(0,8,'EDITORA')]}),
("AGUA MARINHA",{"entities":[(0,12,'EDITORA')]}),
("AVENIDA GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("AGIR",{"entities":[(0,4,'EDITORA')]}),
("ARQUIPELAGO",{"entities":[(0,11,'EDITORA')]}),
("AGAPE",{"entities":[(0,5,'EDITORA')]}),
("AUGUSTUS",{"entities":[(0,8,'EDITORA')]}),
("ARCO IRIS",{"entities":[(0,9,'EDITORA')]}),
("IDEIA ESCRITA",{"entities":[(0,13,'EDITORA')]}),
("ALADDIN",{"entities":[(0,7,'EDITORA')]}),
("S.E. PROJECTA",{"entities":[(0,13,'EDITORA')]}),
("EDITORA AJS",{"entities":[(0,11,'EDITORA')]}),
("AKS",{"entities":[(0,3,'EDITORA')]}),
("AKAL",{"entities":[(0,4,'EDITORA')]}),
("ALINEA",{"entities":[(0,6,'EDITORA')]}),
("S.E. ALUB",{"entities":[(0,9,'EDITORA')]}),
("ALMEIDA GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("ALTERNATIVA",{"entities":[(0,11,'EDITORA')]}),
("S.E. ALFA",{"entities":[(0,9,'EDITORA')]}),
("ALIS",{"entities":[(0,4,'EDITORA')]}),
("ALLES TRADE",{"entities":[(0,11,'EDITORA')]}),
("ALVORADA",{"entities":[(0,8,'EDITORA')]}),
("AREAL EDITORES",{"entities":[(0,14,'EDITORA')]}),
("EL SHADDAI",{"entities":[(0,10,'EDITORA')]}),
("AO LIVRO TECNICO",{"entities":[(0,16,'EDITORA')]}),
("ALVES GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("SISTEMA DE ENSINO LEYA",{"entities":[(0,22,'EDITORA')]}),
("S.E. ANGLO",{"entities":[(0,10,'EDITORA')]}),
("S.E. PEC",{"entities":[(0,8,'EDITORA')]}),
("S.E. COC",{"entities":[(0,8,'EDITORA')]}),
("S.E. PUERI DOMUS",{"entities":[(0,16,'EDITORA')]}),
("S.E. ETAPA",{"entities":[(0,10,'EDITORA')]}),
("S.E. DOM BOSCO",{"entities":[(0,14,'EDITORA')]}),
("S.E. MODULO",{"entities":[(0,11,'EDITORA')]}),
("S.E. SETA",{"entities":[(0,9,'EDITORA')]}),
("S.E. CENTRO INTELIG. HUM",{"entities":[(0,24,'EDITORA')]}),
("S.E. CASA PUBLIC. BRASILEIRA",{"entities":[(0,28,'EDITORA')]}),
("S.E. COMPANHIA DA ESCOLA",{"entities":[(0,24,'EDITORA')]}),
("S.E. SOMA",{"entities":[(0,9,'EDITORA')]}),
("S.E. 3 MILENIO",{"entities":[(0,14,'EDITORA')]}),
("S.E. UNO",{"entities":[(0,8,'EDITORA')]}),
("S.E. OBJETIVO",{"entities":[(0,13,'EDITORA')]}),
("S.E. POSITIVO",{"entities":[(0,13,'EDITORA')]}),
("S.E. SALESIANA",{"entities":[(0,14,'EDITORA')]}),
("S.E. AGUA MARINHA",{"entities":[(0,17,'EDITORA')]}),
("S.E. SIGMA",{"entities":[(0,10,'EDITORA')]}),
("S.E. PITAGORAS",{"entities":[(0,14,'EDITORA')]}),
("S.E. UNIVERSITARIO",{"entities":[(0,18,'EDITORA')]}),
("S.E. PROMOVE",{"entities":[(0,12,'EDITORA')]}),
("S.E. OUTROS",{"entities":[(0,11,'EDITORA')]}),
("S.E. EXPOENTE",{"entities":[(0,13,'EDITORA')]}),
("S.E. ARBOS",{"entities":[(0,10,'EDITORA')]}),
("S.E. PROPRIA ESCOLA",{"entities":[(0,19,'EDITORA')]}),
("ANNABLUME",{"entities":[(0,9,'EDITORA')]}),
("ANCORA",{"entities":[(0,6,'EDITORA')]}),
("ANTROPOSOFICA",{"entities":[(0,13,'EDITORA')]}),
("ANGRA",{"entities":[(0,5,'EDITORA')]}),
("ADONIS",{"entities":[(0,6,'EDITORA')]}),
("A NOITE",{"entities":[(0,7,'EDITORA')]}),
("ANTARES",{"entities":[(0,7,'EDITORA')]}),
("ANAYA",{"entities":[(0,5,'EDITORA')]}),
("APEC",{"entities":[(0,4,'EDITORA')]}),
("APEX",{"entities":[(0,4,'EDITORA')]}),
("S.E. PH",{"entities":[(0,7,'EDITORA')]}),
("S.E. CURSINHO DA POLI",{"entities":[(0,21,'EDITORA')]}),
("APOIO",{"entities":[(0,5,'EDITORA')]}),
("PORA CULTURAL",{"entities":[(0,13,'EDITORA')]}),
("MARCA GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("ARMAZEM DE IDEIAS",{"entities":[(0,17,'EDITORA')]}),
("ARROW BOOKS",{"entities":[(0,11,'EDITORA')]}),
("S.E. APPRO",{"entities":[(0,10,'EDITORA')]}),
("ARQUEIRO",{"entities":[(0,8,'EDITORA')]}),
("SARANDI",{"entities":[(0,7,'EDITORA')]}),
("ARTUS",{"entities":[(0,5,'EDITORA')]}),
("ARVORE DA VIDA",{"entities":[(0,14,'EDITORA')]}),
("ARX",{"entities":[(0,3,'EDITORA')]}),
("ARMAZEM DA CULTURA",{"entities":[(0,18,'EDITORA')]}),
("S.E. SINGULAR",{"entities":[(0,13,'EDITORA')]}),
("AASLE",{"entities":[(0,5,'EDITORA')]}),
("ATUAL",{"entities":[(0,5,'EDITORA')]}),
("ARTMED",{"entities":[(0,6,'EDITORA')]}),
("ARTES E OFICIOS",{"entities":[(0,15,'EDITORA')]}),
("ANITA GARIBALDI",{"entities":[(0,15,'EDITORA')]}),
("S.E. MATHEMA",{"entities":[(0,12,'EDITORA')]}),
("ARTIUM",{"entities":[(0,6,'EDITORA')]}),
("ATLAS",{"entities":[(0,5,'EDITORA')]}),
("ATOMICA",{"entities":[(0,7,'EDITORA')]}),
("ATHENEUM BOOKS",{"entities":[(0,14,'EDITORA')]}),
("ATOMO",{"entities":[(0,5,'EDITORA')]}),
("ARTPRESS",{"entities":[(0,8,'EDITORA')]}),
("ART",{"entities":[(0,3,'EDITORA')]}),
("ATOS",{"entities":[(0,4,'EDITORA')]}),
("S.E ATMO",{"entities":[(0,8,'EDITORA')]}),
("AUTENTICA",{"entities":[(0,9,'EDITORA')]}),
("ATIVA",{"entities":[(0,5,'EDITORA')]}),
("S.E. UNICO",{"entities":[(0,10,'EDITORA')]}),
("S.E. ELITE",{"entities":[(0,10,'EDITORA')]}),
("S.E. UNIVERSO",{"entities":[(0,13,'EDITORA')]}),
("AURORA PRODUCOES",{"entities":[(0,16,'EDITORA')]}),
("AUTORES ASSOCIADOS",{"entities":[(0,18,'EDITORA')]}),
("S.E. ZATTI",{"entities":[(0,10,'EDITORA')]}),
("AVE MARIA",{"entities":[(0,9,'EDITORA')]}),
("AXIS MUNDI",{"entities":[(0,10,'EDITORA')]}),
("AXCEL BOOKS",{"entities":[(0,11,'EDITORA')]}),
("S.E. MAXIMO",{"entities":[(0,11,'EDITORA')]}),
("ARTEXPRESS",{"entities":[(0,10,'EDITORA')]}),
("AYMARA EDUCACAO",{"entities":[(0,15,'EDITORA')]}),
("BAKANA",{"entities":[(0,6,'EDITORA')]}),
("BAOBA",{"entities":[(0,5,'EDITORA')]}),
("BASE EDITORIAL",{"entities":[(0,14,'EDITORA')]}),
("BIBLIOTECA AZUL",{"entities":[(0,15,'EDITORA')]}),
("DESCOBERTA",{"entities":[(0,10,'EDITORA')]}),
("BIBLICA INFANTIL",{"entities":[(0,16,'EDITORA')]}),
("UNIUBE",{"entities":[(0,6,'EDITORA')]}),
("BAMBOOZINHO",{"entities":[(0,11,'EDITORA')]}),
("BERTRAND BRASIL",{"entities":[(0,15,'EDITORA')]}),
("BIBLIOTECA DO EXERCITO",{"entities":[(0,22,'EDITORA')]}),
("CEDIBRA",{"entities":[(0,7,'EDITORA')]}),
("BLUCHER",{"entities":[(0,7,'EDITORA')]}),
("CIDEB",{"entities":[(0,5,'EDITORA')]}),
("S.E. BRADESCO",{"entities":[(0,13,'EDITORA')]}),
("BANDEIRANTE",{"entities":[(0,11,'EDITORA')]}),
("IBID",{"entities":[(0,4,'EDITORA')]}),
("S.E. BARDAL",{"entities":[(0,11,'EDITORA')]}),
("BALDON",{"entities":[(0,6,'EDITORA')]}),
("BEABA",{"entities":[(0,5,'EDITORA')]}),
("BERKELEY",{"entities":[(0,8,'EDITORA')]}),
("BEKA BOOKS",{"entities":[(0,10,'EDITORA')]}),
("BETEL",{"entities":[(0,5,'EDITORA')]}),
("BENVIRA",{"entities":[(0,7,'EDITORA')]}),
("BERLENDIS & VERTECCHIA",{"entities":[(0,22,'EDITORA')]}),
("BESTSELLER",{"entities":[(0,10,'EDITORA')]}),
("BETANIA",{"entities":[(0,7,'EDITORA')]}),
("BAGACO",{"entities":[(0,6,'EDITORA')]}),
("BAGAGEM",{"entities":[(0,7,'EDITORA')]}),
("BERNARDO GUIMARAES",{"entities":[(0,18,'EDITORA')]}),
("BAHIA GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("S.E. BAHIENSE",{"entities":[(0,13,'EDITORA')]}),
("BICHO ESPERTO",{"entities":[(0,13,'EDITORA')]}),
("BIRUTA",{"entities":[(0,6,'EDITORA')]}),
("S.E. BOM JESUS",{"entities":[(0,14,'EDITORA')]}),
("BOM JESUS DOS FRANCISCANOS",{"entities":[(0,26,'EDITORA')]}),
("CASA LYGIA BOJUNGA",{"entities":[(0,18,'EDITORA')]}),
("BOOKMAN",{"entities":[(0,7,'EDITORA')]}),
("BAKER & TAYLOR",{"entities":[(0,14,'EDITORA')]}),
("BLACK CAT READERS",{"entities":[(0,17,'EDITORA')]}),
("BAMBOLE",{"entities":[(0,7,'EDITORA')]}),
("BELASLETRAS",{"entities":[(0,11,'EDITORA')]}),
("BLOCH",{"entities":[(0,5,'EDITORA')]}),
("S.E. BERTOLI",{"entities":[(0,12,'EDITORA')]}),
("BLU",{"entities":[(0,3,'EDITORA')]}),
("BALAO VERMELHO",{"entities":[(0,14,'EDITORA')]}),
("S.E. ABILITY",{"entities":[(0,12,'EDITORA')]}),
("AMBAR",{"entities":[(0,5,'EDITORA')]}),
("BOA COMPANHIA",{"entities":[(0,13,'EDITORA')]}),
("BOLSA NATURAL DO LIVRO",{"entities":[(0,22,'EDITORA')]}),
("BOM SABER",{"entities":[(0,9,'EDITORA')]}),
("BOITATA",{"entities":[(0,7,'EDITORA')]}),
("BOM LIVRO",{"entities":[(0,9,'EDITORA')]}),
("BOM PASTOR",{"entities":[(0,10,'EDITORA')]}),
("BRASPORT",{"entities":[(0,8,'EDITORA')]}),
("CAMPOS BRASIL",{"entities":[(0,13,'EDITORA')]}),
("PLANETA DO BRASIL",{"entities":[(0,17,'EDITORA')]}),
("BJU PRESS",{"entities":[(0,9,'EDITORA')]}),
("PUBLICO",{"entities":[(0,7,'EDITORA')]}),
("EDITORA DO BRASIL",{"entities":[(0,17,'EDITORA')]}),
("BRASIL AMERICA EBAL",{"entities":[(0,19,'EDITORA')]}),
("BR Educação",{"entities":[(0,11,'EDITORA')]}),
("BRAGA",{"entities":[(0,5,'EDITORA')]}),
("BRINQUE BOOK",{"entities":[(0,12,'EDITORA')]}),
("ABRIL",{"entities":[(0,5,'EDITORA')]}),
("BARAUNA",{"entities":[(0,7,'EDITORA')]}),
("BRASILEITURA",{"entities":[(0,12,'EDITORA')]}),
("BRUNO",{"entities":[(0,5,'EDITORA')]}),
("BEST BOOK",{"entities":[(0,9,'EDITORA')]}),
("BICHO DA SEDA",{"entities":[(0,13,'EDITORA')]}),
("S.E. ABRIL",{"entities":[(0,10,'EDITORA')]}),
("BRITISH",{"entities":[(0,7,'EDITORA')]}),
("BEST BOLSO",{"entities":[(0,10,'EDITORA')]}),
("BATTISTEL",{"entities":[(0,9,'EDITORA')]}),
("BANTAM",{"entities":[(0,6,'EDITORA')]}),
("S.E. SETE DE SETEMBRO",{"entities":[(0,21,'EDITORA')]}),
("BOI TEMPO",{"entities":[(0,9,'EDITORA')]}),
("ABACATTE",{"entities":[(0,8,'EDITORA')]}),
("BR1",{"entities":[(0,3,'EDITORA')]}),
("BUREAU",{"entities":[(0,6,'EDITORA')]}),
("BVK",{"entities":[(0,3,'EDITORA')]}),
("BENVOLI",{"entities":[(0,7,'EDITORA')]}),
("BESOURO BOX",{"entities":[(0,11,'EDITORA')]}),
("BOOK EXPRESS",{"entities":[(0,12,'EDITORA')]}),
("BYEWAY BOOKS",{"entities":[(0,12,'EDITORA')]}),
("CANTO A",{"entities":[(0,7,'EDITORA')]}),
("CAB",{"entities":[(0,3,'EDITORA')]}),
("CUCA FRESCA",{"entities":[(0,11,'EDITORA')]}),
("CLARO ENIGMA",{"entities":[(0,12,'EDITORA')]}),
("COMP. DAS LETRINHAS",{"entities":[(0,19,'EDITORA')]}),
("CAMPUS",{"entities":[(0,6,'EDITORA')]}),
("CAMINHO",{"entities":[(0,7,'EDITORA')]}),
("CASA DA PALAVRA",{"entities":[(0,15,'EDITORA')]}),
("CARAMURE",{"entities":[(0,8,'EDITORA')]}),
("CASA DA QUALIDADE",{"entities":[(0,17,'EDITORA')]}),
("CATAVENTO",{"entities":[(0,9,'EDITORA')]}),
("CLUBE DE AUTORES",{"entities":[(0,16,'EDITORA')]}),
("CARTAZ",{"entities":[(0,6,'EDITORA')]}),
("S.E. ABC",{"entities":[(0,8,'EDITORA')]}),
("CALEBE",{"entities":[(0,6,'EDITORA')]}),
("CBFC",{"entities":[(0,4,'EDITORA')]}),
("CLUBE DO LIVRO",{"entities":[(0,14,'EDITORA')]}),
("CAMBRIDGE UNIVERSITY",{"entities":[(0,20,'EDITORA')]}),
("C.C.A.A.",{"entities":[(0,8,'EDITORA')]}),
("CALANGO",{"entities":[(0,7,'EDITORA')]}),
("CAVALO MARINHO",{"entities":[(0,14,'EDITORA')]}),
("CASA CULTURAL",{"entities":[(0,13,'EDITORA')]}),
("MVC",{"entities":[(0,3,'EDITORA')]}),
("DENTRO DA CAIXA",{"entities":[(0,15,'EDITORA')]}),
("CULTURAL BRASIL",{"entities":[(0,15,'EDITORA')]}),
("CASA DO CONTO",{"entities":[(0,13,'EDITORA')]}),
("CIDADANIA",{"entities":[(0,9,'EDITORA')]}),
("EDUNISC",{"entities":[(0,7,'EDITORA')]}),
("CEDRAZ",{"entities":[(0,6,'EDITORA')]}),
("C&E ALFA COMUNICACAO",{"entities":[(0,20,'EDITORA')]}),
("CASA DAS LETRAS",{"entities":[(0,15,'EDITORA')]}),
("CEREJA EDITORA",{"entities":[(0,14,'EDITORA')]}),
("CEJUP",{"entities":[(0,5,'EDITORA')]}),
("CENTRO",{"entities":[(0,6,'EDITORA')]}),
("CARRENHO EDITORIAL",{"entities":[(0,18,'EDITORA')]}),
("CEPE",{"entities":[(0,4,'EDITORA')]}),
("LICEU",{"entities":[(0,5,'EDITORA')]}),
("CRISTA EVANGELICA",{"entities":[(0,17,'EDITORA')]}),
("FCCR",{"entities":[(0,4,'EDITORA')]}),
("CENTER GRAFICA",{"entities":[(0,14,'EDITORA')]}),
("CANGURU",{"entities":[(0,7,'EDITORA')]}),
("CHAIM",{"entities":[(0,5,'EDITORA')]}),
("CHIADO",{"entities":[(0,6,'EDITORA')]}),
("S.E. FRANCISCANO",{"entities":[(0,16,'EDITORA')]}),
("EDICOES CHOCOLATE",{"entities":[(0,17,'EDITORA')]}),
("CHAMPAGNAT",{"entities":[(0,10,'EDITORA')]}),
("CHRISTUS",{"entities":[(0,8,'EDITORA')]}),
("TASCHEN",{"entities":[(0,7,'EDITORA')]}),
("CIRANDA CULTURAL",{"entities":[(0,16,'EDITORA')]}),
("CIDADE NOVA",{"entities":[(0,11,'EDITORA')]}),
("ACADEMIA DE INTELIGENCIA",{"entities":[(0,24,'EDITORA')]}),
("CIENCIA HOJE",{"entities":[(0,12,'EDITORA')]}),
("CALLIS",{"entities":[(0,6,'EDITORA')]}),
("CIENCIA MODERNA",{"entities":[(0,15,'EDITORA')]}),
("CARIOCA",{"entities":[(0,7,'EDITORA')]}),
("CIENCIA E PAZ",{"entities":[(0,13,'EDITORA')]}),
("CIRCULO DO LIVRO",{"entities":[(0,16,'EDITORA')]}),
("CIVILIZACAO BRASILEIRA",{"entities":[(0,22,'EDITORA')]}),
("CJA EDICOES",{"entities":[(0,11,'EDITORA')]}),
("CAMARA BRAS. JOVENS ESCRITOR",{"entities":[(0,28,'EDITORA')]}),
("CLARANTO",{"entities":[(0,8,'EDITORA')]}),
("COLIBRI",{"entities":[(0,7,'EDITORA')]}),
("CELD LEON DENIS",{"entities":[(0,15,'EDITORA')]}),
("CLE",{"entities":[(0,3,'EDITORA')]}),
("CASTALIA",{"entities":[(0,8,'EDITORA')]}),
("ELENCO",{"entities":[(0,6,'EDITORA')]}),
("CALIBAN",{"entities":[(0,7,'EDITORA')]}),
("CLIO",{"entities":[(0,4,'EDITORA')]}),
("CHILDS PLAY",{"entities":[(0,11,'EDITORA')]}),
("S.E. LUZ DO SABER",{"entities":[(0,17,'EDITORA')]}),
("CULTRIX",{"entities":[(0,7,'EDITORA')]}),
("CARAMELO",{"entities":[(0,8,'EDITORA')]}),
("COMEDIA CEARENSE",{"entities":[(0,16,'EDITORA')]}),
("CASA AMARELA",{"entities":[(0,12,'EDITORA')]}),
("CMF EDITORA",{"entities":[(0,11,'EDITORA')]}),
("COMUNIGRAF",{"entities":[(0,10,'EDITORA')]}),
("COMUNIQUE",{"entities":[(0,9,'EDITORA')]}),
("COMUNICACAO",{"entities":[(0,11,'EDITORA')]}),
("CMQ",{"entities":[(0,3,'EDITORA')]}),
("CNA",{"entities":[(0,3,'EDITORA')]}),
("CONHECER",{"entities":[(0,8,'EDITORA')]}),
("CONE",{"entities":[(0,4,'EDITORA')]}),
("S.E CONQUISTA",{"entities":[(0,13,'EDITORA')]}),
("COLLINS",{"entities":[(0,7,'EDITORA')]}),
("CIA DAS CORES",{"entities":[(0,13,'EDITORA')]}),
("CODECRI",{"entities":[(0,7,'EDITORA')]}),
("COMPOR",{"entities":[(0,6,'EDITORA')]}),
("CONCORDE",{"entities":[(0,8,'EDITORA')]}),
("CORISCO",{"entities":[(0,7,'EDITORA')]}),
("COSMOPOLITA",{"entities":[(0,11,'EDITORA')]}),
("CPAD",{"entities":[(0,4,'EDITORA')]}),
("CASA PUBLICADORA BRASILEIRA",{"entities":[(0,27,'EDITORA')]}),
("PUC",{"entities":[(0,3,'EDITORA')]}),
("CASA DO PSICOLOGO",{"entities":[(0,17,'EDITORA')]}),
("S.E. CPV",{"entities":[(0,8,'EDITORA')]}),
("CASA DAS ARTES",{"entities":[(0,14,'EDITORA')]}),
("CRIANCAS CRIATIVAS",{"entities":[(0,18,'EDITORA')]}),
("CRESCER",{"entities":[(0,7,'EDITORA')]}),
("CAROCHINHA",{"entities":[(0,10,'EDITORA')]}),
("CRISTA UNIDA",{"entities":[(0,12,'EDITORA')]}),
("LC CORREIA",{"entities":[(0,10,'EDITORA')]}),
("CAMARGO",{"entities":[(0,7,'EDITORA')]}),
("CRIAR EDICOES",{"entities":[(0,13,'EDITORA')]}),
("COMUNICARTE",{"entities":[(0,11,'EDITORA')]}),
("CAMINHO SUAVE",{"entities":[(0,13,'EDITORA')]}),
("CASA DE LIVROS",{"entities":[(0,14,'EDITORA')]}),
("UESC",{"entities":[(0,4,'EDITORA')]}),
("COSAC & NAIFY",{"entities":[(0,13,'EDITORA')]}),
("CASSOL",{"entities":[(0,6,'EDITORA')]}),
("S.E. SUCESSO",{"entities":[(0,12,'EDITORA')]}),
("CONSTRUIR",{"entities":[(0,9,'EDITORA')]}),
("CORTEZ",{"entities":[(0,6,'EDITORA')]}),
("DIDACTA",{"entities":[(0,7,'EDITORA')]}),
("CATEDRAL DAS LETRAS",{"entities":[(0,19,'EDITORA')]}),
("ACTION",{"entities":[(0,6,'EDITORA')]}),
("CATA SONHO",{"entities":[(0,10,'EDITORA')]}),
("COMETA",{"entities":[(0,6,'EDITORA')]}),
("CULTURA CRISTA",{"entities":[(0,14,'EDITORA')]}),
("CULTURA",{"entities":[(0,7,'EDITORA')]}),
("CUORE",{"entities":[(0,5,'EDITORA')]}),
("CONVIVER",{"entities":[(0,8,'EDITORA')]}),
("CARAVANSARAI",{"entities":[(0,12,'EDITORA')]}),
("CORVARA",{"entities":[(0,7,'EDITORA')]}),
("CONTEXTO",{"entities":[(0,8,'EDITORA')]}),
("CAIXA VERDE",{"entities":[(0,11,'EDITORA')]}),
("CUBZAC",{"entities":[(0,6,'EDITORA')]}),
("DIMENSAO",{"entities":[(0,8,'EDITORA')]}),
("DAMADA",{"entities":[(0,6,'EDITORA')]}),
("DBA",{"entities":[(0,3,'EDITORA')]}),
("EBD",{"entities":[(0,3,'EDITORA')]}),
("ALFA EDUCATIVA",{"entities":[(0,14,'EDITORA')]}),
("DOUBLEDAY",{"entities":[(0,9,'EDITORA')]}),
("DUBLINENSE",{"entities":[(0,10,'EDITORA')]}),
("DESCUBRA",{"entities":[(0,8,'EDITORA')]}),
("DIFUSAO CULTURAL DO LIVRO",{"entities":[(0,25,'EDITORA')]}),
("DUAS CIDADES",{"entities":[(0,12,'EDITORA')]}),
("DCE",{"entities":[(0,3,'EDITORA')]}),
("CUNHA DESIGNERS",{"entities":[(0,15,'EDITORA')]}),
("EDITORA DE CULTURA",{"entities":[(0,18,'EDITORA')]}),
("DIVULGACAO CULTURAL",{"entities":[(0,19,'EDITORA')]}),
("CONRAD LIVROS",{"entities":[(0,13,'EDITORA')]}),
("CODICE",{"entities":[(0,6,'EDITORA')]}),
("CIDADELA EDITORIAL",{"entities":[(0,18,'EDITORA')]}),
("EDINUMEN",{"entities":[(0,8,'EDITORA')]}),
("EDITORA DAS DUAS",{"entities":[(0,16,'EDITORA')]}),
("DEVIR",{"entities":[(0,5,'EDITORA')]}),
("DECIFRA",{"entities":[(0,7,'EDITORA')]}),
("DIFUSION",{"entities":[(0,8,'EDITORA')]}),
("DE LEITURA",{"entities":[(0,10,'EDITORA')]}),
("S.E. TENDENCIA",{"entities":[(0,14,'EDITORA')]}),
("DESIDERATA",{"entities":[(0,10,'EDITORA')]}),
("DELTA",{"entities":[(0,5,'EDITORA')]}),
("DG EDITORA",{"entities":[(0,10,'EDITORA')]}),
("DEGASPARI",{"entities":[(0,9,'EDITORA')]}),
("DOCES HISTORIAS",{"entities":[(0,15,'EDITORA')]}),
("DIMAC",{"entities":[(0,5,'EDITORA')]}),
("MEDIACAO",{"entities":[(0,8,'EDITORA')]}),
("DIDIER",{"entities":[(0,6,'EDITORA')]}),
("DIFEL",{"entities":[(0,5,'EDITORA')]}),
("PLATAFORMA DIGITAL",{"entities":[(0,18,'EDITORA')]}),
("S.E. DINAMICO",{"entities":[(0,13,'EDITORA')]}),
("DIDATICA PAULISTA",{"entities":[(0,17,'EDITORA')]}),
("DIDATICA SUL",{"entities":[(0,12,'EDITORA')]}),
("DIVISAO",{"entities":[(0,7,'EDITORA')]}),
("DARBY CREEK",{"entities":[(0,11,'EDITORA')]}),
("ALAUDE",{"entities":[(0,6,'EDITORA')]}),
("DLC",{"entities":[(0,3,'EDITORA')]}),
("CANDLEWICK PRESS",{"entities":[(0,16,'EDITORA')]}),
("DEMOCRITO ROCHA",{"entities":[(0,15,'EDITORA')]}),
("DINAMICA EDITORA",{"entities":[(0,16,'EDITORA')]}),
("RONDONIANA",{"entities":[(0,10,'EDITORA')]}),
("DIFUSAO NACIONAL DO LIVRO",{"entities":[(0,25,'EDITORA')]}),
("DINAMUS",{"entities":[(0,7,'EDITORA')]}),
("DOMINIO PUBLICO",{"entities":[(0,15,'EDITORA')]}),
("CASA DO NOVO AUTOR",{"entities":[(0,18,'EDITORA')]}),
("CODEX",{"entities":[(0,5,'EDITORA')]}),
("DP&A",{"entities":[(0,4,'EDITORA')]}),
("CATEDRA",{"entities":[(0,7,'EDITORA')]}),
("PRESTIGIO",{"entities":[(0,9,'EDITORA')]}),
("DALILA RODRIGUES FIGUEIREDO",{"entities":[(0,27,'EDITORA')]}),
("DRAGONFLY BOOKS",{"entities":[(0,15,'EDITORA')]}),
("DARKSIDE BOOKS",{"entities":[(0,14,'EDITORA')]}),
("DU SIGNE",{"entities":[(0,8,'EDITORA')]}),
("ED. DSOP",{"entities":[(0,8,'EDITORA')]}),
("ANDERSEN",{"entities":[(0,8,'EDITORA')]}),
("DIANTE DO TRONO",{"entities":[(0,15,'EDITORA')]}),
("SAL DA TERRA",{"entities":[(0,12,'EDITORA')]}),
("DORAVANTE",{"entities":[(0,9,'EDITORA')]}),
("EDUFMA",{"entities":[(0,6,'EDITORA')]}),
("DUMMAR",{"entities":[(0,6,'EDITORA')]}),
("DUNYA",{"entities":[(0,5,'EDITORA')]}),
("DAUDT DESIGN",{"entities":[(0,12,'EDITORA')]}),
("VAAD",{"entities":[(0,4,'EDITORA')]}),
("DISNEY PRESS",{"entities":[(0,12,'EDITORA')]}),
("EDICOES DE ARTE",{"entities":[(0,15,'EDITORA')]}),
("EBM EDITORA",{"entities":[(0,11,'EDITORA')]}),
("EDUCACAO E CIA",{"entities":[(0,14,'EDITORA')]}),
("EDICARE",{"entities":[(0,7,'EDITORA')]}),
("EMECE EDITORA",{"entities":[(0,13,'EDITORA')]}),
("ESCRITA FINA",{"entities":[(0,12,'EDITORA')]}),
("EN CLAVE",{"entities":[(0,8,'EDITORA')]}),
("ESCARLATE",{"entities":[(0,9,'EDITORA')]}),
("ED.34",{"entities":[(0,5,'EDITORA')]}),
("EDIFICANTES",{"entities":[(0,11,'EDITORA')]}),
("EDEBE",{"entities":[(0,5,'EDITORA')]}),
("DIDATICA CIENTIFICA",{"entities":[(0,19,'EDITORA')]}),
("EDE",{"entities":[(0,3,'EDITORA')]}),
("EDELBRA",{"entities":[(0,7,'EDITORA')]}),
("EDUFF",{"entities":[(0,5,'EDITORA')]}),
("ESCOLA DA INTELIGENCIA",{"entities":[(0,22,'EDITORA')]}),
("EDICON",{"entities":[(0,6,'EDITORA')]}),
("EDESPLAN",{"entities":[(0,8,'EDITORA')]}),
("EDUA",{"entities":[(0,4,'EDITORA')]}),
("EDELSA",{"entities":[(0,6,'EDITORA')]}),
("S.E. EDUTEC",{"entities":[(0,11,'EDITORA')]}),
("EDUFBA",{"entities":[(0,6,'EDITORA')]}),
("EDELVIVES",{"entities":[(0,9,'EDITORA')]}),
("GUERRA EDIZIONI",{"entities":[(0,15,'EDITORA')]}),
("ELSEVIER EDITORA",{"entities":[(0,16,'EDITORA')]}),
("ESFERA",{"entities":[(0,6,'EDITORA')]}),
("EDUFJF",{"entities":[(0,6,'EDITORA')]}),
("EFUTURE",{"entities":[(0,7,'EDITORA')]}),
("EDUFU",{"entities":[(0,5,'EDITORA')]}),
("GGEGRAF",{"entities":[(0,7,'EDITORA')]}),
("VIDEIRA",{"entities":[(0,7,'EDITORA')]}),
("ESPACO JURIDICO",{"entities":[(0,15,'EDITORA')]}),
("EKO",{"entities":[(0,3,'EDITORA')]}),
("ELDORADO",{"entities":[(0,8,'EDITORA')]}),
("ELEVACAO",{"entities":[(0,8,'EDITORA')]}),
("SELF",{"entities":[(0,4,'EDITORA')]}),
("ELI EDITORA",{"entities":[(0,11,'EDITORA')]}),
("ELEMENTAR",{"entities":[(0,9,'EDITORA')]}),
("ELUE",{"entities":[(0,4,'EDITORA')]}),
("S.E. ELEVA",{"entities":[(0,10,'EDITORA')]}),
("ALAMEDA",{"entities":[(0,7,'EDITORA')]}),
("TEMPO",{"entities":[(0,5,'EDITORA')]}),
("ESTUDOS AMAZONICOS",{"entities":[(0,18,'EDITORA')]}),
("BARSA PLANETA",{"entities":[(0,13,'EDITORA')]}),
("ENCONTRO",{"entities":[(0,8,'EDITORA')]}),
("S.E. ENERGIA",{"entities":[(0,12,'EDITORA')]}),
("ENSINAMENTO",{"entities":[(0,11,'EDITORA')]}),
("ENOVUS PUBLICACOES",{"entities":[(0,18,'EDITORA')]}),
("EDIOURO",{"entities":[(0,7,'EDITORA')]}),
("EPP EDITORA",{"entities":[(0,11,'EDITORA')]}),
("EDIPAR",{"entities":[(0,6,'EDITORA')]}),
("ESPASA CALPE",{"entities":[(0,12,'EDITORA')]}),
("EXPRESSAO GRAFICA",{"entities":[(0,17,'EDITORA')]}),
("EPM EDITORA",{"entities":[(0,11,'EDITORA')]}),
("EDIPUCRS",{"entities":[(0,8,'EDITORA')]}),
("E.P.U",{"entities":[(0,5,'EDITORA')]}),
("EXPRESS",{"entities":[(0,7,'EDITORA')]}),
("NOVA ERA",{"entities":[(0,8,'EDITORA')]}),
("ERCA",{"entities":[(0,4,'EDITORA')]}),
("ERICA",{"entities":[(0,5,'EDITORA')]}),
("PRICE STERN",{"entities":[(0,11,'EDITORA')]}),
("EdPUCRS",{"entities":[(0,7,'EDITORA')]}),
("EDUCARTE",{"entities":[(0,8,'EDITORA')]}),
("EXPOENTE",{"entities":[(0,8,'EDITORA')]}),
("ESCRITURAS",{"entities":[(0,10,'EDITORA')]}),
("S.E. IESD",{"entities":[(0,9,'EDITORA')]}),
("ESTACAO DAS FORMAS",{"entities":[(0,18,'EDITORA')]}),
("ESPIRAL",{"entities":[(0,7,'EDITORA')]}),
("ESQUINA DA PALAVRA",{"entities":[(0,18,'EDITORA')]}),
("ESTACAO LIBERDADE",{"entities":[(0,17,'EDITORA')]}),
("ETICA",{"entities":[(0,5,'EDITORA')]}),
("EDUTEC",{"entities":[(0,6,'EDITORA')]}),
("S.E. ETICO",{"entities":[(0,10,'EDITORA')]}),
("ENTERPRISE IDIOMAS",{"entities":[(0,18,'EDITORA')]}),
("ENTRELINHAS",{"entities":[(0,11,'EDITORA')]}),
("EDITUS",{"entities":[(0,6,'EDITORA')]}),
("EXITUS",{"entities":[(0,6,'EDITORA')]}),
("EURO IMPALA",{"entities":[(0,11,'EDITORA')]}),
("EDUEM",{"entities":[(0,5,'EDITORA')]}),
("EDUSP",{"entities":[(0,5,'EDITORA')]}),
("EUROPA",{"entities":[(0,6,'EDITORA')]}),
("EVOLUTIVO",{"entities":[(0,9,'EDITORA')]}),
("EDITORIAL 25",{"entities":[(0,12,'EDITORA')]}),
("EVOLUIR",{"entities":[(0,7,'EDITORA')]}),
("EXATO",{"entities":[(0,5,'EDITORA')]}),
("EXPRESSAO E CULTURA",{"entities":[(0,19,'EDITORA')]}),
("TEXTO EDITORES",{"entities":[(0,14,'EDITORA')]}),
("EASY FOR YOU",{"entities":[(0,12,'EDITORA')]}),
("ESCARIZ",{"entities":[(0,7,'EDITORA')]}),
("FRANCISCO ALVES",{"entities":[(0,15,'EDITORA')]}),
("FABRICA DE LIVROS",{"entities":[(0,17,'EDITORA')]}),
("FACTASH",{"entities":[(0,7,'EDITORA')]}),
("FACES",{"entities":[(0,5,'EDITORA')]}),
("FALA MENINO",{"entities":[(0,11,'EDITORA')]}),
("FUNALFA",{"entities":[(0,7,'EDITORA')]}),
("FAPI",{"entities":[(0,4,'EDITORA')]}),
("FRANCO",{"entities":[(0,6,'EDITORA')]}),
("FREITAS BASTOS",{"entities":[(0,14,'EDITORA')]}),
("FABRICA DE IDEIAS",{"entities":[(0,17,'EDITORA')]}),
("FCO EDITORA",{"entities":[(0,11,'EDITORA')]}),
("FUNDACAO DORINA",{"entities":[(0,15,'EDITORA')]}),
("EDFMA",{"entities":[(0,5,'EDITORA')]}),
("FED. ESPIRITA BRASILEIRA",{"entities":[(0,24,'EDITORA')]}),
("FTD EDUCACAO",{"entities":[(0,12,'EDITORA')]}),
("FABER & FABER",{"entities":[(0,13,'EDITORA')]}),
("FEDERACAO ISRAELITA",{"entities":[(0,19,'EDITORA')]}),
("FENAME",{"entities":[(0,6,'EDITORA')]}),
("FENIX",{"entities":[(0,5,'EDITORA')]}),
("APRENDER",{"entities":[(0,8,'EDITORA')]}),
("EFEITO GRAFICO",{"entities":[(0,14,'EDITORA')]}),
("FIEL",{"entities":[(0,4,'EDITORA')]}),
("GIRAFINHA",{"entities":[(0,9,'EDITORA')]}),
("KINGFISHER",{"entities":[(0,10,'EDITORA')]}),
("FISK",{"entities":[(0,4,'EDITORA')]}),
("FRANKLIN COVEY",{"entities":[(0,14,'EDITORA')]}),
("FLAMMARION",{"entities":[(0,10,'EDITORA')]}),
("FLORES E CULTURA",{"entities":[(0,16,'EDITORA')]}),
("FELIPE EDICOES",{"entities":[(0,14,'EDITORA')]}),
("FOLHA PUBLICA",{"entities":[(0,13,'EDITORA')]}),
("FUNDO NACIONAL DE CULTURA",{"entities":[(0,25,'EDITORA')]}),
("FOLIO",{"entities":[(0,5,'EDITORA')]}),
("FORMAR",{"entities":[(0,6,'EDITORA')]}),
("FONTANA",{"entities":[(0,7,'EDITORA')]}),
("FORENSE UNIVERSITARIA",{"entities":[(0,21,'EDITORA')]}),
("FORT GRAFICA",{"entities":[(0,12,'EDITORA')]}),
("FONTE VIVA",{"entities":[(0,10,'EDITORA')]}),
("FUNDACAO PERSEU ABRAMO",{"entities":[(0,22,'EDITORA')]}),
("EDITORA UFPR",{"entities":[(0,12,'EDITORA')]}),
("FRASE",{"entities":[(0,5,'EDITORA')]}),
("FREITAG",{"entities":[(0,7,'EDITORA')]}),
("GRAFER",{"entities":[(0,6,'EDITORA')]}),
("FRANCIS",{"entities":[(0,7,'EDITORA')]}),
("FASA",{"entities":[(0,4,'EDITORA')]}),
("FORMATO",{"entities":[(0,7,'EDITORA')]}),
("FTD",{"entities":[(0,3,'EDITORA')]}),
("FINO TRACO",{"entities":[(0,10,'EDITORA')]}),
("FUNARTE",{"entities":[(0,7,'EDITORA')]}),
("FUMARC",{"entities":[(0,6,'EDITORA')]}),
("FUNDAMENTOS",{"entities":[(0,11,'EDITORA')]}),
("FUTURA",{"entities":[(0,6,'EDITORA')]}),
("FZE",{"entities":[(0,3,'EDITORA')]}),
("GABARITO",{"entities":[(0,8,'EDITORA')]}),
("GAIVOTA",{"entities":[(0,7,'EDITORA')]}),
("GRAAL",{"entities":[(0,5,'EDITORA')]}),
("GRAO",{"entities":[(0,4,'EDITORA')]}),
("GARAPUVU",{"entities":[(0,8,'EDITORA')]}),
("GARAMOND",{"entities":[(0,8,'EDITORA')]}),
("GRALHA AZUL",{"entities":[(0,11,'EDITORA')]}),
("GIBIM GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("BRASIL GRAFICA",{"entities":[(0,14,'EDITORA')]}),
("GUARDA CHUVA",{"entities":[(0,12,'EDITORA')]}),
("GERACAO DIGITAL",{"entities":[(0,15,'EDITORA')]}),
("GOLDMANN",{"entities":[(0,8,'EDITORA')]}),
("AGE",{"entities":[(0,3,'EDITORA')]}),
("GEEK EDITORA",{"entities":[(0,12,'EDITORA')]}),
("GERMINAL",{"entities":[(0,8,'EDITORA')]}),
("GENTE",{"entities":[(0,5,'EDITORA')]}),
("GERACAO",{"entities":[(0,7,'EDITORA')]}),
("GRAFIS",{"entities":[(0,6,'EDITORA')]}),
("GAMA FILHO",{"entities":[(0,10,'EDITORA')]}),
("MARQUES GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("DO POVO GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("GRAFSET",{"entities":[(0,7,'EDITORA')]}),
("CULTURA GOIANIA",{"entities":[(0,15,'EDITORA')]}),
("GEOGRAFICA",{"entities":[(0,10,'EDITORA')]}),
("GIZ EDITORIAL",{"entities":[(0,13,'EDITORA')]}),
("IGLU",{"entities":[(0,4,'EDITORA')]}),
("S.E. GPI",{"entities":[(0,8,'EDITORA')]}),
("OETINGER VERLAG",{"entities":[(0,15,'EDITORA')]}),
("COGNITIVA",{"entities":[(0,9,'EDITORA')]}),
("GALERA HIPERMIDIA",{"entities":[(0,17,'EDITORA')]}),
("GAIA",{"entities":[(0,4,'EDITORA')]}),
("GIBRAN",{"entities":[(0,6,'EDITORA')]}),
("GAUDI",{"entities":[(0,5,'EDITORA')]}),
("GIRAMUNDO",{"entities":[(0,9,'EDITORA')]}),
("GIOSTRI",{"entities":[(0,7,'EDITORA')]}),
("GIRASSOL",{"entities":[(0,8,'EDITORA')]}),
("GLOBO",{"entities":[(0,5,'EDITORA')]}),
("LINGUATIVA",{"entities":[(0,10,'EDITORA')]}),
("GLOBAL",{"entities":[(0,6,'EDITORA')]}),
("LCR GRAFICA",{"entities":[(0,11,'EDITORA')]}),
("GALLIMARD",{"entities":[(0,9,'EDITORA')]}),
("S.E. GENESE",{"entities":[(0,11,'EDITORA')]}),
("GENIUS",{"entities":[(0,6,'EDITORA')]}),
("S.E GENOMA",{"entities":[(0,10,'EDITORA')]}),
("S.E. GENIO",{"entities":[(0,10,'EDITORA')]}),
("S.E. GENOS",{"entities":[(0,10,'EDITORA')]}),
("ALEGROS",{"entities":[(0,7,'EDITORA')]}),
("S.E. LOG",{"entities":[(0,8,'EDITORA')]}),
("GOODSEED",{"entities":[(0,8,'EDITORA')]}),
("POLIGLOTA",{"entities":[(0,9,'EDITORA')]}),
("CENTRAL GOSPEL",{"entities":[(0,14,'EDITORA')]}),
("GALPAO DO LIVRO",{"entities":[(0,15,'EDITORA')]}),
("PARADIGMA",{"entities":[(0,9,'EDITORA')]}),
("S.E. POSIGRAF",{"entities":[(0,13,'EDITORA')]}),
("G4",{"entities":[(0,2,'EDITORA')]}),
("GRAFFITI",{"entities":[(0,8,'EDITORA')]}),
("GREENSYSTEM",{"entities":[(0,11,'EDITORA')]}),
("ORIGAMI",{"entities":[(0,7,'EDITORA')]}),
("GARNIER",{"entities":[(0,7,'EDITORA')]}),
("GROUND",{"entities":[(0,6,'EDITORA')]}),
("S.E. GARRA",{"entities":[(0,10,'EDITORA')]}),
("GRADIVA",{"entities":[(0,7,'EDITORA')]}),
("GREENWICH",{"entities":[(0,9,'EDITORA')]}),
("GRYPHUS",{"entities":[(0,7,'EDITORA')]}),
("GETSEMANI",{"entities":[(0,9,'EDITORA')]}),
("SANTA TEREZINHA GRAFICA",{"entities":[(0,23,'EDITORA')]}),
("GATAFUNHO",{"entities":[(0,9,'EDITORA')]}),
("S.E. DIGITALLY",{"entities":[(0,14,'EDITORA')]}),
("SEGMENTO",{"entities":[(0,8,'EDITORA')]}),
("GTR",{"entities":[(0,3,'EDITORA')]}),
("GUANABARA KOOGAN",{"entities":[(0,16,'EDITORA')]}),
("NOVA AGUILAR",{"entities":[(0,12,'EDITORA')]}),
("GUTENBERG",{"entities":[(0,9,'EDITORA')]}),
("NAVEGAR",{"entities":[(0,7,'EDITORA')]}),
("GILDI VERLAZ",{"entities":[(0,12,'EDITORA')]}),
("HACHETTE",{"entities":[(0,8,'EDITORA')]}),
("HANNAH EDITORA",{"entities":[(0,14,'EDITORA')]}),
("HARLEQUIN",{"entities":[(0,9,'EDITORA')]}),
("HARA",{"entities":[(0,4,'EDITORA')]}),
("HATIER DIDIER",{"entities":[(0,13,'EDITORA')]}),
("HARBRA",{"entities":[(0,6,'EDITORA')]}),
("HANDY BOOKS",{"entities":[(0,11,'EDITORA')]}),
("HAMBURG",{"entities":[(0,7,'EDITORA')]}),
("HARCOURT",{"entities":[(0,8,'EDITORA')]}),
("HARDCOVER",{"entities":[(0,9,'EDITORA')]}),
("HOLIDAY HOUSE",{"entities":[(0,13,'EDITORA')]}),
("HEDRA",{"entities":[(0,5,'EDITORA')]}),
("HEINLE E HEINLE",{"entities":[(0,15,'EDITORA')]}),
("HEMUS",{"entities":[(0,5,'EDITORA')]}),
("HGF",{"entities":[(0,3,'EDITORA')]}),
("HAGNOS",{"entities":[(0,6,'EDITORA')]}),
("HORTA GRANDE",{"entities":[(0,12,'EDITORA')]}),
("HEISNEMANN",{"entities":[(0,10,'EDITORA')]}),
("HISPANO",{"entities":[(0,7,'EDITORA')]}),
("HUMAITA",{"entities":[(0,7,'EDITORA')]}),
("HORTOLANDIA GRAFICA",{"entities":[(0,19,'EDITORA')]}),
("HALLEY",{"entities":[(0,6,'EDITORA')]}),
("HAESE MATHEMATICS",{"entities":[(0,17,'EDITORA')]}),
("HOUGHTON MIFFLIN",{"entities":[(0,16,'EDITORA')]}),
("HUMANIDADES",{"entities":[(0,11,'EDITORA')]}),
("S.E HANNAH",{"entities":[(0,10,'EDITORA')]}),
("HINTERLANDIA",{"entities":[(0,12,'EDITORA')]}),
("IN HOUSE",{"entities":[(0,8,'EDITORA')]}),
("HIPOCAMPUS",{"entities":[(0,10,'EDITORA')]}),
("HARPER COLLINS",{"entities":[(0,14,'EDITORA')]}),
("HAPPY BOOKS",{"entities":[(0,11,'EDITORA')]}),
("TECNOARTE",{"entities":[(0,9,'EDITORA')]}),
("HEMISFERIO SUL",{"entities":[(0,14,'EDITORA')]}),
("EDITORA HTC",{"entities":[(0,11,'EDITORA')]}),
("HUEBER",{"entities":[(0,6,'EDITORA')]}),
("HUB EDITORIAL",{"entities":[(0,13,'EDITORA')]}),
("HUMANITAS",{"entities":[(0,9,'EDITORA')]}),
("HELVECIA",{"entities":[(0,8,'EDITORA')]}),
("HYPERION BOOKS",{"entities":[(0,14,'EDITORA')]}),
("HELBLING LANGUAGES",{"entities":[(0,18,'EDITORA')]}),
("ZERO HORA",{"entities":[(0,9,'EDITORA')]}),
("MAIA",{"entities":[(0,4,'EDITORA')]}),
("IBGE",{"entities":[(0,4,'EDITORA')]}),
("IBIS",{"entities":[(0,4,'EDITORA')]}),
("IBEP",{"entities":[(0,4,'EDITORA')]}),
("IBRASA",{"entities":[(0,6,'EDITORA')]}),
("IBPEX",{"entities":[(0,5,'EDITORA')]}),
("CEDIC",{"entities":[(0,5,'EDITORA')]}),
("ICONE",{"entities":[(0,5,'EDITORA')]}),
("ID EDITORA",{"entities":[(0,10,'EDITORA')]}),
("IDEA",{"entities":[(0,4,'EDITORA')]}),
("INDIGO BRASIL",{"entities":[(0,13,'EDITORA')]}),
("IDIOMAGIC",{"entities":[(0,9,'EDITORA')]}),
("IDEIAS E LETRAS",{"entities":[(0,15,'EDITORA')]}),
("IEL",{"entities":[(0,3,'EDITORA')]}),
("SISTEMA DE ENSINO - IESDE",{"entities":[(0,25,'EDITORA')]}),
("INFORMAL",{"entities":[(0,8,'EDITORA')]}),
("CORIFEU",{"entities":[(0,7,'EDITORA')]}),
("IHGRN",{"entities":[(0,5,'EDITORA')]}),
("IMEPH",{"entities":[(0,5,'EDITORA')]}),
("GAILIVRO",{"entities":[(0,8,'EDITORA')]}),
("DELANTI",{"entities":[(0,7,'EDITORA')]}),
("LIBERIA",{"entities":[(0,7,'EDITORA')]}),
("ILUMINURAS",{"entities":[(0,10,'EDITORA')]}),
("IMAGEM GRAFICA",{"entities":[(0,14,'EDITORA')]}),
("S.E. IMAGO DEI",{"entities":[(0,14,'EDITORA')]}),
("IMPRENSA",{"entities":[(0,8,'EDITORA')]}),
("S.E. IMPULSE",{"entities":[(0,12,'EDITORA')]}),
("INOJOSA",{"entities":[(0,7,'EDITORA')]}),
("INED",{"entities":[(0,4,'EDITORA')]}),
("INTEGRA CONFESSIONAIS",{"entities":[(0,21,'EDITORA')]}),
("INDIE",{"entities":[(0,5,'EDITORA')]}),
("LUMINE",{"entities":[(0,6,'EDITORA')]}),
("Integra",{"entities":[(0,7,'EDITORA')]}),
("INMENT",{"entities":[(0,6,'EDITORA')]}),
("INSULAR",{"entities":[(0,7,'EDITORA')]}),
("S. E. INTEGRA",{"entities":[(0,13,'EDITORA')]}),
("OPCAO GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("INOVA",{"entities":[(0,5,'EDITORA')]}),
("IMPALA",{"entities":[(0,6,'EDITORA')]}),
("IPDH EDICOES",{"entities":[(0,12,'EDITORA')]}),
("IPIRANGA",{"entities":[(0,8,'EDITORA')]}),
("S.E. APRIMORE",{"entities":[(0,13,'EDITORA')]}),
("IMPRELL",{"entities":[(0,7,'EDITORA')]}),
("IMPETUS",{"entities":[(0,7,'EDITORA')]}),
("IRIAR",{"entities":[(0,5,'EDITORA')]}),
("IMPERIAL NOVO MILENIO",{"entities":[(0,21,'EDITORA')]}),
("S.E. IRIUM",{"entities":[(0,10,'EDITORA')]}),
("S.E. IPIRANGA",{"entities":[(0,13,'EDITORA')]}),
("IRES",{"entities":[(0,4,'EDITORA')]}),
("IATRIA",{"entities":[(0,6,'EDITORA')]}),
("SIVADI",{"entities":[(0,6,'EDITORA')]}),
("ITATIAIA",{"entities":[(0,8,'EDITORA')]}),
("S. E. ITAGYBA",{"entities":[(0,13,'EDITORA')]}),
("INTELLIGENCE",{"entities":[(0,12,'EDITORA')]}),
("IRMAOS VITALE",{"entities":[(0,13,'EDITORA')]}),
("JAC",{"entities":[(0,3,'EDITORA')]}),
("JANGADA",{"entities":[(0,7,'EDITORA')]}),
("JB GRAFICA",{"entities":[(0,10,'EDITORA')]}),
("JBC",{"entities":[(0,3,'EDITORA')]}),
("JABUTI",{"entities":[(0,6,'EDITORA')]}),
("EDJOVEM",{"entities":[(0,7,'EDITORA')]}),
("S.E. JOSE FERREIRA",{"entities":[(0,18,'EDITORA')]}),
("JORNAL DA CIDADE GRAFICA",{"entities":[(0,24,'EDITORA')]}),
("JOLLY LEARNING",{"entities":[(0,14,'EDITORA')]}),
("JM GRAFICA",{"entities":[(0,10,'EDITORA')]}),
("MESTRE JOU",{"entities":[(0,10,'EDITORA')]}),
("JOSE OLYMPIO",{"entities":[(0,12,'EDITORA')]}),
("S.E. JEAN PIAGET",{"entities":[(0,16,'EDITORA')]}),
("JRC",{"entities":[(0,3,'EDITORA')]}),
("JUJUBA",{"entities":[(0,6,'EDITORA')]}),
("JUERP",{"entities":[(0,5,'EDITORA')]}),
("JURUA",{"entities":[(0,5,'EDITORA')]}),
("JUST",{"entities":[(0,4,'EDITORA')]}),
("JOVEM",{"entities":[(0,5,'EDITORA')]}),
("JW INFORMATICA",{"entities":[(0,14,'EDITORA')]}),
("K 2",{"entities":[(0,3,'EDITORA')]}),
("KALIMERA",{"entities":[(0,8,'EDITORA')]}),
("KAPOK",{"entities":[(0,5,'EDITORA')]}),
("PINK AND BLUE FREEDON",{"entities":[(0,21,'EDITORA')]}),
("KCM GRAFICA",{"entities":[(0,11,'EDITORA')]}),
("KACO GRAFICA",{"entities":[(0,12,'EDITORA')]}),
("KEILINHA",{"entities":[(0,8,'EDITORA')]}),
("KLICK",{"entities":[(0,5,'EDITORA')]}),
("KINDERBOOKS",{"entities":[(0,11,'EDITORA')]}),
("KALANDRAKA",{"entities":[(0,10,'EDITORA')]}),
("KLETT",{"entities":[(0,5,'EDITORA')]}),
("KOMEDI",{"entities":[(0,6,'EDITORA')]}),
("PARALOGIKE",{"entities":[(0,10,'EDITORA')]}),
("KELPS",{"entities":[(0,5,'EDITORA')]}),
("KRIEDUC",{"entities":[(0,7,'EDITORA')]}),
("KROTON",{"entities":[(0,6,'EDITORA')]}),
("S.E. KAIROS",{"entities":[(0,11,'EDITORA')]}),
("KITS",{"entities":[(0,4,'EDITORA')]}),
("KINTAW",{"entities":[(0,6,'EDITORA')]}),
("KUARUP",{"entities":[(0,6,'EDITORA')]}),
("LABORCIENCIA",{"entities":[(0,12,'EDITORA')]}),
("LACERDA",{"entities":[(0,7,'EDITORA')]}),
("LADYBIRD",{"entities":[(0,8,'EDITORA')]}),
("LAFONTE",{"entities":[(0,7,'EDITORA')]}),
("LAGO",{"entities":[(0,4,'EDITORA')]}),
("LAROUSSE",{"entities":[(0,8,'EDITORA')]}),
("LA SALLE",{"entities":[(0,8,'EDITORA')]}),
("LABORTEXTO",{"entities":[(0,10,'EDITORA')]}),
("PALAVRA & PRECE",{"entities":[(0,15,'EDITORA')]}),
("LAZULI",{"entities":[(0,6,'EDITORA')]}),
("S.E. ULBRA",{"entities":[(0,10,'EDITORA')]}),
("LERBAN",{"entities":[(0,6,'EDITORA')]}),
("LIBRIS",{"entities":[(0,6,'EDITORA')]}),
("LIBERATO",{"entities":[(0,8,'EDITORA')]}),
("LUZ E CORES",{"entities":[(0,11,'EDITORA')]}),
("LANDMARK",{"entities":[(0,8,'EDITORA')]}),
("VALE DAS LETRAS",{"entities":[(0,15,'EDITORA')]}),
("LANDY",{"entities":[(0,5,'EDITORA')]}),
("LE",{"entities":[(0,2,'EDITORA')]}),
("LETRA CAPITAL",{"entities":[(0,13,'EDITORA')]}),
("LEITURA XXI",{"entities":[(0,11,'EDITORA')]}),
("LETRAS E LETRAS",{"entities":[(0,15,'EDITORA')]}),
("LEMOS",{"entities":[(0,5,'EDITORA')]}),
("LER E ESCREVER",{"entities":[(0,14,'EDITORA')]}),
("LETRAS E ARTES",{"entities":[(0,14,'EDITORA')]}),
("LEUD",{"entities":[(0,4,'EDITORA')]}),
("LEXIKON",{"entities":[(0,7,'EDITORA')]}),
("LEYA",{"entities":[(0,4,'EDITORA')]}),
("LEARNING FACTORY",{"entities":[(0,16,'EDITORA')]}),
("LIVRARIA DA FISICA",{"entities":[(0,18,'EDITORA')]}),
("MULTIFOCO",{"entities":[(0,9,'EDITORA')]}),
("LONGMAN",{"entities":[(0,7,'EDITORA')]}),
("ALGAIDA",{"entities":[(0,7,'EDITORA')]}),
("LGE",{"entities":[(0,3,'EDITORA')]}),
("FUN LANGUAGES",{"entities":[(0,13,'EDITORA')]}),
("LINGUA GERAL",{"entities":[(0,12,'EDITORA')]}),
("LOGICA DO PENSAR",{"entities":[(0,16,'EDITORA')]}),
("LEGO",{"entities":[(0,4,'EDITORA')]}),
("LANGENSCHEIDT",{"entities":[(0,13,'EDITORA')]}),
("LIBERTAD",{"entities":[(0,8,'EDITORA')]}),
("COMPANHIA DAS LETRAS",{"entities":[(0,20,'EDITORA')]}),
("LIVRO IDEAL",{"entities":[(0,11,'EDITORA')]}),
("S.E. BERNOULLI",{"entities":[(0,14,'EDITORA')]}),
("LINHA GRAFICA",{"entities":[(0,13,'EDITORA')]}),
("LIRA",{"entities":[(0,4,'EDITORA')]}),
("OBELISCO",{"entities":[(0,8,'EDITORA')]}),
("LITTERE",{"entities":[(0,7,'EDITORA')]}),
("LILIVROS",{"entities":[(0,8,'EDITORA')]}),
("LELLO IRMAOS",{"entities":[(0,12,'EDITORA')]}),
("SOLER",{"entities":[(0,5,'EDITORA')]}),
("ROVELLE",{"entities":[(0,7,'EDITORA')]}),
("ULISSEIA",{"entities":[(0,8,'EDITORA')]}),
("W LIMA EDITORA",{"entities":[(0,14,'EDITORA')]}),
("ALMA EDIZIONI",{"entities":[(0,13,'EDITORA')]}),
("ACADEMIA MIRIM DAS LETRAS",{"entities":[(0,25,'EDITORA')]}),
("ELEMENTOS",{"entities":[(0,9,'EDITORA')]}),
("DULCINEIA",{"entities":[(0,9,'EDITORA')]}),
("TERCEIRO NOME",{"entities":[(0,13,'EDITORA')]}),
("REINO DAS LETRAS",{"entities":[(0,16,'EDITORA')]}),
("GOLD LIONS",{"entities":[(0,10,'EDITORA')]}),
("S.E. VENTO LESTE",{"entities":[(0,16,'EDITORA')]}),
("S.E. LANYNE",{"entities":[(0,11,'EDITORA')]}),
("ALELUIA",{"entities":[(0,7,'EDITORA')]}),
("CARACOL",{"entities":[(0,7,'EDITORA')]}),
("LOGOS",{"entities":[(0,5,'EDITORA')]}),
("LOWES",{"entities":[(0,5,'EDITORA')]}),
("L&PM",{"entities":[(0,4,'EDITORA')]}),
("PRELUDIO",{"entities":[(0,8,'EDITORA')]}),
("LETRAS BRASILEIRAS",{"entities":[(0,18,'EDITORA')]}),
("BALIEIRO",{"entities":[(0,8,'EDITORA')]}),
("LISA",{"entities":[(0,4,'EDITORA')]}),
("DUBOLSINHO",{"entities":[(0,10,'EDITORA')]}),
("S.E. LOURENCO CASTANHO",{"entities":[(0,22,'EDITORA')]}),
("S.E LIVRE",{"entities":[(0,9,'EDITORA')]}),
("LASER",{"entities":[(0,5,'EDITORA')]}),
("SOBRAL",{"entities":[(0,6,'EDITORA')]}),
("COMPANHIA DE BOLSO",{"entities":[(0,18,'EDITORA')]}),
("LITTERIS",{"entities":[(0,8,'EDITORA')]}),
("LETRA ENCANTADA",{"entities":[(0,15,'EDITORA')]}),
("LTC",{"entities":[(0,3,'EDITORA')]}),
("LIMITADA",{"entities":[(0,8,'EDITORA')]}),
("TREM DAS LETRAS",{"entities":[(0,15,'EDITORA')]}),
("LTR",{"entities":[(0,3,'EDITORA')]}),
("LITTLE BROWN",{"entities":[(0,12,'EDITORA')]}),
("LUCERNA",{"entities":[(0,7,'EDITORA')]}),
("LUDO",{"entities":[(0,4,'EDITORA')]}),
("LUMEM",{"entities":[(0,5,'EDITORA')]}),
("LUA DE PAPEL",{"entities":[(0,12,'EDITORA')]}),
("LUNARDELLI",{"entities":[(0,10,'EDITORA')]}),
("LUZ E VIDA",{"entities":[(0,10,'EDITORA')]}),
("LETRA VIVA",{"entities":[(0,10,'EDITORA')]}),
("LA VENTANA",{"entities":[(0,10,'EDITORA')]}),
("LIVRO PRONTO",{"entities":[(0,12,'EDITORA')]}),
("LEW",{"entities":[(0,3,'EDITORA')]}),
("LEXIA",{"entities":[(0,5,'EDITORA')]}),
("LOYOLA",{"entities":[(0,6,'EDITORA')]}),
("AMARILYS",{"entities":[(0,8,'EDITORA')]}),
("MODERNA",{"entities":[(0,7,'EDITORA')]}),
("MERCADO ABERTO",{"entities":[(0,14,'EDITORA')]}),
("MAAYANOT",{"entities":[(0,8,'EDITORA')]}),
("MACMILLAN",{"entities":[(0,9,'EDITORA')]}),
("MANDARIM",{"entities":[(0,8,'EDITORA')]}),
("MACGRAW-HILL",{"entities":[(0,12,'EDITORA')]}),
("S. E. IEMAR",{"entities":[(0,11,'EDITORA')]}),
("EDITORA MAJORIS",{"entities":[(0,15,'EDITORA')]}),
("MANOLE",{"entities":[(0,6,'EDITORA')]}),
("MANATI",{"entities":[(0,6,'EDITORA')]}),
("MARINATT'OS",{"entities":[(0,11,'EDITORA')]}),
("MADRAS",{"entities":[(0,6,'EDITORA')]}),
("MAUAD",{"entities":[(0,5,'EDITORA')]}),
("S.E. MARY WARD",{"entities":[(0,14,'EDITORA')]}),
("S.E. MAXI",{"entities":[(0,9,'EDITORA')]}),
("MAZZA",{"entities":[(0,5,'EDITORA')]}),
("BRASILIENSE",{"entities":[(0,11,'EDITORA')]}),
("MIRABOLANTE",{"entities":[(0,11,'EDITORA')]}),
("M BOOKS",{"entities":[(0,7,'EDITORA')]}),
("MACKRON BROOKS",{"entities":[(0,14,'EDITORA')]}),
("OMNISCIENCIA",{"entities":[(0,12,'EDITORA')]}),
("MANECO",{"entities":[(0,6,'EDITORA')]}),
("MERCURYO",{"entities":[(0,8,'EDITORA')]}),
("MUNDIAL",{"entities":[(0,7,'EDITORA')]}),
("MEDIAÇÃO",{"entities":[(0,8,'EDITORA')]}),
("MUNDO JOVEM",{"entities":[(0,11,'EDITORA')]}),
("MIND LAB",{"entities":[(0,8,'EDITORA')]}),
("MODELO EDITORIAL",{"entities":[(0,16,'EDITORA')]}),
("MELHORAMENTOS",{"entities":[(0,13,'EDITORA')]}),
("MECA",{"entities":[(0,4,'EDITORA')]}),
("MUNDO EDITORIAL",{"entities":[(0,15,'EDITORA')]}),
("MERITOS",{"entities":[(0,7,'EDITORA')]}),
("MELBOOKS",{"entities":[(0,8,'EDITORA')]}),
("MEMORIAS FUTURAS",{"entities":[(0,16,'EDITORA')]}),
("MUNDUS ENEM",{"entities":[(0,11,'EDITORA')]}),
("GERMAPE",{"entities":[(0,7,'EDITORA')]}),
("MERIDIANO",{"entities":[(0,9,'EDITORA')]}),
("METAFORA",{"entities":[(0,8,'EDITORA')]}),
("MZ EDITORA",{"entities":[(0,10,'EDITORA')]}),
("MARTINS FONTES",{"entities":[(0,14,'EDITORA')]}),
("FLAMULA",{"entities":[(0,7,'EDITORA')]}),
("MFC",{"entities":[(0,3,'EDITORA')]}),
("MUSICA EM FAMILIA",{"entities":[(0,17,'EDITORA')]}),
("S.E. MARISTA - SME",{"entities":[(0,18,'EDITORA')]}),
("MAGA PEDAGOGICA",{"entities":[(0,15,'EDITORA')]}),
("MAGISTER",{"entities":[(0,8,'EDITORA')]}),
("S.E. MIGUEL COUTO",{"entities":[(0,17,'EDITORA')]}),
("MIDIOGRAF",{"entities":[(0,9,'EDITORA')]}),
("S.E. GEO",{"entities":[(0,8,'EDITORA')]}),
("GRAMOFONE",{"entities":[(0,9,'EDITORA')]}),
("RAMALIVROS",{"entities":[(0,10,'EDITORA')]}),
("MG GOMES",{"entities":[(0,8,'EDITORA')]}),
("MAHARA",{"entities":[(0,6,'EDITORA')]}),
("MASCARENHAS",{"entities":[(0,11,'EDITORA')]}),
("S.E. IBEP",{"entities":[(0,9,'EDITORA')]}),
("MIGUILIM",{"entities":[(0,8,'EDITORA')]}),
("META",{"entities":[(0,4,'EDITORA')]}),
("S.E. GOMESI",{"entities":[(0,11,'EDITORA')]}),
("MINDEN",{"entities":[(0,6,'EDITORA')]}),
("S.E. MACKENZIE",{"entities":[(0,14,'EDITORA')]}),
("MIND LAB - MENTEINOVADORA",{"entities":[(0,25,'EDITORA')]}),
("MUNDO EM LEITURA",{"entities":[(0,16,'EDITORA')]}),
("MAISON DES LANGUES EDITIONS",{"entities":[(0,27,'EDITORA')]}),
("MARY & ELIARDO",{"entities":[(0,14,'EDITORA')]}),
("MARTINS LIVREIRO",{"entities":[(0,16,'EDITORA')]}),
("MULHERES",{"entities":[(0,8,'EDITORA')]}),
("MALTESE",{"entities":[(0,7,'EDITORA')]}),
("LUMUS",{"entities":[(0,5,'EDITORA')]}),
("MULTIMIDIA",{"entities":[(0,10,'EDITORA')]}),
("CMS",{"entities":[(0,3,'EDITORA')]}),
("METRO CUBICO",{"entities":[(0,12,'EDITORA')]}),
("MINERVA",{"entities":[(0,7,'EDITORA')]}),
("MONECO",{"entities":[(0,6,'EDITORA')]}),
("MUNDO MIRIM",{"entities":[(0,11,'EDITORA')]}),
("S.E. MENTES NOTAVEIS",{"entities":[(0,20,'EDITORA')]}),
("CLIMACO",{"entities":[(0,7,'EDITORA')]}),
("DIVINA MISERICORDIA",{"entities":[(0,19,'EDITORA')]}),
("MODULO",{"entities":[(0,6,'EDITORA')]}),
("MOMENTOS DE MAGIA",{"entities":[(0,17,'EDITORA')]}),
("MOSAICO",{"entities":[(0,7,'EDITORA')]}),
("METODO",{"entities":[(0,6,'EDITORA')]}),
("MOVPALAVRAS",{"entities":[(0,11,'EDITORA')]}),
("MARCO ZERO",{"entities":[(0,10,'EDITORA')]}),
("MM PUBLICATIONS",{"entities":[(0,15,'EDITORA')]}),
("MPA MULTIMIDIA",{"entities":[(0,14,'EDITORA')]}),
("MARCA PAGINA",{"entities":[(0,12,'EDITORA')]}),
("CONTEMPORANEA",{"entities":[(0,13,'EDITORA')]}),
("PROEM",{"entities":[(0,5,'EDITORA')]}),
("MARIA",{"entities":[(0,5,'EDITORA')]}),
("MR BENS",{"entities":[(0,7,'EDITORA')]}),
("S.E. SANTA MARIA",{"entities":[(0,16,'EDITORA')]}),
("MARISTA",{"entities":[(0,7,'EDITORA')]}),
("S.E. SER",{"entities":[(0,8,'EDITORA')]}),
("S.E. MATHUES SOLUCOES SISTEMA",{"entities":[(0,29,'EDITORA')]}),
("MTB",{"entities":[(0,3,'EDITORA')]}),
("MARTIN CLARET",{"entities":[(0,13,'EDITORA')]}),
("S.E. MOTIVO",{"entities":[(0,11,'EDITORA')]}),
("MULTIPLO",{"entities":[(0,8,'EDITORA')]}),
("M3",{"entities":[(0,2,'EDITORA')]}),
("MAIS ATIVOS",{"entities":[(0,11,'EDITORA')]}),
("MATRIX",{"entities":[(0,6,'EDITORA')]}),
("MATERDEY",{"entities":[(0,8,'EDITORA')]}),
("MUSICAL BUCHER",{"entities":[(0,14,'EDITORA')]}),
("MUNDO E MISSAO",{"entities":[(0,14,'EDITORA')]}),
("MUIRAQUITA",{"entities":[(0,10,'EDITORA')]}),
("MULTILIVRO",{"entities":[(0,10,'EDITORA')]}),
("MUNDO CRISTAO",{"entities":[(0,13,'EDITORA')]}),
("MUSIMED",{"entities":[(0,7,'EDITORA')]}),
("MULTIPLICIDADE",{"entities":[(0,14,'EDITORA')]}),
("MV1 - S.E.",{"entities":[(0,10,'EDITORA')]}),
("MOVIMENTO",{"entities":[(0,9,'EDITORA')]}),
("MEMORIA VISUAL",{"entities":[(0,14,'EDITORA')]}),
("S.E. EXATO",{"entities":[(0,10,'EDITORA')]}),
("S.E.  AYMARA",{"entities":[(0,11,'EDITORA')]}),
("NACIONAL",{"entities":[(0,8,'EDITORA')]}),
("NAO ADOTA LIVROS",{"entities":[(0,16,'EDITORA')]}),
("NOVA BAHIA",{"entities":[(0,10,'EDITORA')]}),
("S.E. NOBEL",{"entities":[(0,10,'EDITORA')]}),
("GUENA BUSSUIS",{"entities":[(0,13,'EDITORA')]}),
("CANONE EDITORIAL",{"entities":[(0,16,'EDITORA')]}),
("S.E. CONVIVER",{"entities":[(0,13,'EDITORA')]}),
("CANCAO NOVA",{"entities":[(0,11,'EDITORA')]}),
("NOVA DIDATICA",{"entities":[(0,13,'EDITORA')]}),
("S.E. NOTA 10",{"entities":[(0,12,'EDITORA')]}),
("S.E. CNEC",{"entities":[(0,9,'EDITORA')]}),
("NEEMI",{"entities":[(0,5,'EDITORA')]}),
("S.E. INED",{"entities":[(0,9,'EDITORA')]}),
("NEMO",{"entities":[(0,4,'EDITORA')]}),
("NOVA ESPIRAL",{"entities":[(0,12,'EDITORA')]}),
("NEW WAY",{"entities":[(0,7,'EDITORA')]}),
("NOVA FRONTEIRA",{"entities":[(0,14,'EDITORA')]}),
("UNIGRAF",{"entities":[(0,7,'EDITORA')]}),
("SINAI",{"entities":[(0,5,'EDITORA')]}),
("NICOLA MILANO",{"entities":[(0,13,'EDITORA')]}),
("NANKIM",{"entities":[(0,6,'EDITORA')]}),
("NOVOS LIVROS",{"entities":[(0,12,'EDITORA')]}),
("NOVALDADE",{"entities":[(0,9,'EDITORA')]}),
("NOVA ALIANCA",{"entities":[(0,12,'EDITORA')]}),
("NOVA ALEXANDRIA",{"entities":[(0,15,'EDITORA')]}),
("NORMA",{"entities":[(0,5,'EDITORA')]}),
("NOVO HORIZONTE",{"entities":[(0,14,'EDITORA')]}),
("UNIVERSO",{"entities":[(0,8,'EDITORA')]}),
("NOBEL",{"entities":[(0,5,'EDITORA')]}),
("NOVA CULTURAL",{"entities":[(0,13,'EDITORA')]}),
("NORDICA",{"entities":[(0,7,'EDITORA')]}),
("NOVO SECULO",{"entities":[(0,11,'EDITORA')]}),
("S.E. PRINCIPIA",{"entities":[(0,14,'EDITORA')]}),
("ANEP",{"entities":[(0,4,'EDITORA')]}),
("UNIPRO",{"entities":[(0,6,'EDITORA')]}),
("NOVA REPUBLICA",{"entities":[(0,14,'EDITORA')]}),
("NERIAH",{"entities":[(0,6,'EDITORA')]}),
("NOVO RUMO",{"entities":[(0,9,'EDITORA')]}),
("NOSSA CULTURA",{"entities":[(0,13,'EDITORA')]}),
("NOVO ESTILO",{"entities":[(0,11,'EDITORA')]}),
("INTA",{"entities":[(0,4,'EDITORA')]}),
("S.E. NETBIL",{"entities":[(0,11,'EDITORA')]}),
("DANTES EDITORA",{"entities":[(0,14,'EDITORA')]}),
("NOVA LETRA",{"entities":[(0,10,'EDITORA')]}),
("NATIONAL GEOGRA",{"entities":[(0,15,'EDITORA')]}),
("NATHAN",{"entities":[(0,6,'EDITORA')]}),
("NELSON THORNES",{"entities":[(0,14,'EDITORA')]}),
("NOVO TEMPO",{"entities":[(0,10,'EDITORA')]}),
("INTEGRARE",{"entities":[(0,9,'EDITORA')]}),
("NUCLEO",{"entities":[(0,6,'EDITORA')]}),
("NUPE",{"entities":[(0,4,'EDITORA')]}),
("NATUREZA",{"entities":[(0,8,'EDITORA')]}),
("NOOVHA AMERICA",{"entities":[(0,14,'EDITORA')]}),
("NOVA GERACAO",{"entities":[(0,12,'EDITORA')]}),
("VINHA",{"entities":[(0,5,'EDITORA')]}),
("NAVEGANTES",{"entities":[(0,10,'EDITORA')]}),
("NOVATEC",{"entities":[(0,7,'EDITORA')]}),
("OBJETIVA",{"entities":[(0,8,'EDITORA')]}),
("OBJETIVO",{"entities":[(0,8,'EDITORA')]}),
("ARCO EDUCAÇÃO",{"entities":[(0,13,'EDITORA')]}),
("EDICOES 70",{"entities":[(0,10,'EDITORA')]}),
("FOCO",{"entities":[(0,4,'EDITORA')]}),
("FUN.OSWALDO CRUZ",{"entities":[(0,16,'EDITORA')]}),
("ADOS",{"entities":[(0,4,'EDITORA')]}),
("OFICINA DAS FINANCAS",{"entities":[(0,20,'EDITORA')]}),
("ODYSSEUS",{"entities":[(0,8,'EDITORA')]}),
("OFICINA DO AUTOR",{"entities":[(0,16,'EDITORA')]}),
("OFICINA DO LIVRO",{"entities":[(0,16,'EDITORA')]}),
("OFICINA DA PALAVRA",{"entities":[(0,18,'EDITORA')]}),
("OFICINA DE TEXTOS",{"entities":[(0,17,'EDITORA')]}),
("KALANGO",{"entities":[(0,7,'EDITORA')]}),
("S.E. ORION",{"entities":[(0,10,'EDITORA')]}),
("OLHO D`AGUA",{"entities":[(0,11,'EDITORA')]}),
("S.E. OLIMPO",{"entities":[(0,11,'EDITORA')]}),
("POMAR",{"entities":[(0,5,'EDITORA')]}),
("OMNI",{"entities":[(0,4,'EDITORA')]}),
("OCEANO",{"entities":[(0,6,'EDITORA')]}),
("DECOR",{"entities":[(0,5,'EDITORA')]}),
("OPEE",{"entities":[(0,4,'EDITORA')]}),
("OPIRUS EDITORA",{"entities":[(0,14,'EDITORA')]}),
("OPUS MASTER",{"entities":[(0,11,'EDITORA')]}),
("ORIENTACAO CULTURAL",{"entities":[(0,19,'EDITORA')]}),
("OSBORNE",{"entities":[(0,7,'EDITORA')]}),
("OTI",{"entities":[(0,3,'EDITORA')]}),
("S.E. EVOLUTIVO",{"entities":[(0,14,'EDITORA')]}),
("MOTIVOS",{"entities":[(0,7,'EDITORA')]}),
("OXFORD UNIVERSITY PRESS DO EDITORA DO BRASIL - OUP",{"entities":[(0,50,'EDITORA')]}),
("OZE",{"entities":[(0,3,'EDITORA')]}),
("EDICOES PAULINAS",{"entities":[(0,16,'EDITORA')]}),
("PALABRITAS",{"entities":[(0,10,'EDITORA')]}),
("S.E. JPAG",{"entities":[(0,9,'EDITORA')]}),
("PIA EDICOES",{"entities":[(0,11,'EDITORA')]}),
("PAKATATU",{"entities":[(0,8,'EDITORA')]}),
("PALAVRA MAGICA",{"entities":[(0,14,'EDITORA')]}),
("PANORAMA",{"entities":[(0,8,'EDITORA')]}),
("PAPIRUS",{"entities":[(0,7,'EDITORA')]}),
("PARCERIA",{"entities":[(0,8,'EDITORA')]}),
("PAULUS",{"entities":[(0,6,'EDITORA')]}),
("PAZ E TERRA",{"entities":[(0,11,'EDITORA')]}),
("PUBLISHER BRASIL",{"entities":[(0,16,'EDITORA')]}),
("CEPA",{"entities":[(0,4,'EDITORA')]}),
("PANDA BOOKS",{"entities":[(0,11,'EDITORA')]}),
("S.E. P D E",{"entities":[(0,10,'EDITORA')]}),
("S.E. APRENDER",{"entities":[(0,13,'EDITORA')]}),
("PENDAO REAL",{"entities":[(0,11,'EDITORA')]}),
("PERSPECTIVA",{"entities":[(0,11,'EDITORA')]}),
("PEDRO I",{"entities":[(0,7,'EDITORA')]}),
("PE DA LETRA",{"entities":[(0,11,'EDITORA')]}),
("UNIMEP",{"entities":[(0,6,'EDITORA')]}),
("PENGUIN BOOKS",{"entities":[(0,13,'EDITORA')]}),
("PEREIRA DA SILVA",{"entities":[(0,16,'EDITORA')]}),
("S.E PLURI EDUCACIONAL",{"entities":[(0,21,'EDITORA')]}),
("PETIT - ESPIRITA",{"entities":[(0,16,'EDITORA')]}),
("EXPRESSAO POPULAR",{"entities":[(0,17,'EDITORA')]}),
("ESPECIFICA",{"entities":[(0,10,'EDITORA')]}),
("PUFFIN BOOKS",{"entities":[(0,12,'EDITORA')]}),
("PAIS E FILHOS",{"entities":[(0,13,'EDITORA')]}),
("PAISAGEM",{"entities":[(0,8,'EDITORA')]}),
("S.E. GRAPHER",{"entities":[(0,12,'EDITORA')]}),
("PHORTE",{"entities":[(0,6,'EDITORA')]}),
("ALEPH",{"entities":[(0,5,'EDITORA')]}),
("INDEPENDENTE",{"entities":[(0,12,'EDITORA')]}),
("UNICAMP",{"entities":[(0,7,'EDITORA')]}),
("EDIPLAT",{"entities":[(0,7,'EDITORA')]}),
("IPE",{"entities":[(0,3,'EDITORA')]}),
("PRIMEIRA IMPRESSAO",{"entities":[(0,18,'EDITORA')]}),
("PIEMME",{"entities":[(0,6,'EDITORA')]}),
("PRINCIPIO",{"entities":[(0,9,'EDITORA')]}),
("PIONEIRA",{"entities":[(0,8,'EDITORA')]}),
("S.E. PASSEIO",{"entities":[(0,12,'EDITORA')]}),
("TRAPIA",{"entities":[(0,6,'EDITORA')]}),
("UESPI",{"entities":[(0,5,'EDITORA')]}),
("PROJETO EDUCANDO",{"entities":[(0,16,'EDITORA')]}),
("PLAZA JANES",{"entities":[(0,11,'EDITORA')]}),
("PANCAST",{"entities":[(0,7,'EDITORA')]}),
("PORTOKALOS",{"entities":[(0,10,'EDITORA')]}),
("PINAKOTHEKE",{"entities":[(0,11,'EDITORA')]}),
("PALLAS",{"entities":[(0,6,'EDITORA')]}),
("APLAC",{"entities":[(0,5,'EDITORA')]}),
("PLEIADE",{"entities":[(0,7,'EDITORA')]}),
("PULO DO GATO",{"entities":[(0,12,'EDITORA')]}),
("PLANETA INFANTIL",{"entities":[(0,16,'EDITORA')]}),
("PLANETA JOVEM",{"entities":[(0,13,'EDITORA')]}),
("PALLOTI",{"entities":[(0,7,'EDITORA')]}),
("PAULINAS",{"entities":[(0,8,'EDITORA')]}),
("PLANETA RIO",{"entities":[(0,11,'EDITORA')]}),
("S.E. PLURAL",{"entities":[(0,11,'EDITORA')]}),
("POLLUX",{"entities":[(0,6,'EDITORA')]}),
("PEDROSA MONTEIRO",{"entities":[(0,16,'EDITORA')]}),
("PARAMOUNT",{"entities":[(0,9,'EDITORA')]}),
("PRUMO",{"entities":[(0,5,'EDITORA')]}),
("PREMIUS",{"entities":[(0,7,'EDITORA')]}),
("NITPRESS",{"entities":[(0,8,'EDITORA')]}),
("PENALUX",{"entities":[(0,7,'EDITORA')]}),
("PANINI BOOKS",{"entities":[(0,12,'EDITORA')]}),
("PENSIERI",{"entities":[(0,8,'EDITORA')]}),
("PEIXOTO NETO",{"entities":[(0,12,'EDITORA')]}),
("POLIGRAFICA",{"entities":[(0,11,'EDITORA')]}),
("POLICARPO",{"entities":[(0,9,'EDITORA')]}),
("POEMA",{"entities":[(0,5,'EDITORA')]}),
("PONTES",{"entities":[(0,6,'EDITORA')]}),
("PORTUGAL",{"entities":[(0,8,'EDITORA')]}),
("PAPARBACK",{"entities":[(0,9,'EDITORA')]}),
("COMPANHIA DA ESCOLA",{"entities":[(0,19,'EDITORA')]}),
("PURPOSEFUL DESIGN",{"entities":[(0,17,'EDITORA')]}),
("IMPRESSAO GRAFICA",{"entities":[(0,17,'EDITORA')]}),
("PEIROPOLIS",{"entities":[(0,10,'EDITORA')]}),
("PAPA LIVRO",{"entities":[(0,10,'EDITORA')]}),
("EDITORA PENSARTE",{"entities":[(0,16,'EDITORA')]}),
("PROTEXTO",{"entities":[(0,8,'EDITORA')]}),
("PQS",{"entities":[(0,3,'EDITORA')]}),
("PRODUCOES ARTISTICAS",{"entities":[(0,20,'EDITORA')]}),
("PARABOLA",{"entities":[(0,8,'EDITORA')]}),
("PRESENCA",{"entities":[(0,8,'EDITORA')]}),
("PRISMA",{"entities":[(0,6,'EDITORA')]}),
("PARALELA",{"entities":[(0,8,'EDITORA')]}),
("PROJETO",{"entities":[(0,7,'EDITORA')]}),
("PROMESSA",{"entities":[(0,8,'EDITORA')]}),
("PRINTIPUC",{"entities":[(0,9,'EDITORA')]}),
("PROSA E VERSO",{"entities":[(0,13,'EDITORA')]}),
("S.E. SPAE",{"entities":[(0,9,'EDITORA')]}),
("POLISABER",{"entities":[(0,9,'EDITORA')]}),
("MUNDO ESPANOL",{"entities":[(0,13,'EDITORA')]}),
("PEARSON",{"entities":[(0,7,'EDITORA')]}),
("PRENTICE HALL",{"entities":[(0,13,'EDITORA')]}),
("TRADICAO PLANALTO",{"entities":[(0,17,'EDITORA')]}),
("IMPRINTA",{"entities":[(0,8,'EDITORA')]}),
("PAULO DE TARSO LIVRARIA",{"entities":[(0,23,'EDITORA')]}),
("PORTO",{"entities":[(0,5,'EDITORA')]}),
("PUBLIFOLHA",{"entities":[(0,10,'EDITORA')]}),
("PUGLIESI",{"entities":[(0,8,'EDITORA')]}),
("PUBLIT",{"entities":[(0,6,'EDITORA')]}),
("PAETEC VERLAG",{"entities":[(0,13,'EDITORA')]}),
("PONTO E VIRGULA",{"entities":[(0,15,'EDITORA')]}),
("PAO E VINHO",{"entities":[(0,11,'EDITORA')]}),
("POSITIVO",{"entities":[(0,8,'EDITORA')]}),
("PROVENZANO",{"entities":[(0,10,'EDITORA')]}),
("PIXEL MIDIA",{"entities":[(0,11,'EDITORA')]}),
("EXEMPLAR",{"entities":[(0,8,'EDITORA')]}),
("POTYLIVRO",{"entities":[(0,9,'EDITORA')]}),
("TUPYNANQUIM",{"entities":[(0,11,'EDITORA')]}),
("QUADRINHOS NA CIA",{"entities":[(0,17,'EDITORA')]}),
("QUADRAN KIDS",{"entities":[(0,12,'EDITORA')]}),
("QUINTETO",{"entities":[(0,8,'EDITORA')]}),
("QUARTICA",{"entities":[(0,8,'EDITORA')]}),
("QUALOGIC",{"entities":[(0,8,'EDITORA')]}),
("MARQUES SARAIVA",{"entities":[(0,15,'EDITORA')]}),
("CEMAQUE",{"entities":[(0,7,'EDITORA')]}),
("QUARK PRESS",{"entities":[(0,11,'EDITORA')]}),
("QUADRANTE",{"entities":[(0,9,'EDITORA')]}),
("EQUATORIAL",{"entities":[(0,10,'EDITORA')]}),
("QUALITYMARK",{"entities":[(0,11,'EDITORA')]}),
("QUALOGIC",{"entities":[(0,8,'EDITORA')]}),
("QUICKPRINTER",{"entities":[(0,12,'EDITORA')]}),
("QUARTET",{"entities":[(0,7,'EDITORA')]}),
("FUNDACAO QUIXOTE",{"entities":[(0,16,'EDITORA')]}),
("RABONI",{"entities":[(0,6,'EDITORA')]}),
("RAZAO CULTURAL",{"entities":[(0,14,'EDITORA')]}),
("SIEART",{"entities":[(0,6,'EDITORA')]}),
("S.E. GGE",{"entities":[(0,8,'EDITORA')]}),
("RANDOM HOUSE",{"entities":[(0,12,'EDITORA')]}),
("S.E. MULTIRAO",{"entities":[(0,13,'EDITORA')]}),
("LIVRO RAPIDO",{"entities":[(0,12,'EDITORA')]}),
("RECORD",{"entities":[(0,6,'EDITORA')]}),
("REDE CATOLICA DE ENSINO",{"entities":[(0,23,'EDITORA')]}),
("S.E. REDE CRISTA DE EDUCACAO",{"entities":[(0,28,'EDITORA')]}),
("RICHMOND",{"entities":[(0,8,'EDITORA')]}),
("RODA E CIA",{"entities":[(0,10,'EDITORA')]}),
("CLARIDADE",{"entities":[(0,9,'EDITORA')]}),
("RECANTO",{"entities":[(0,7,'EDITORA')]}),
("SCHROEDEL",{"entities":[(0,9,'EDITORA')]}),
("RANDAL",{"entities":[(0,6,'EDITORA')]}),
("RELUME DUMARA",{"entities":[(0,13,'EDITORA')]}),
("BRAINSTORE",{"entities":[(0,10,'EDITORA')]}),
("RECIFE",{"entities":[(0,6,'EDITORA')]}),
("R&F",{"entities":[(0,3,'EDITORA')]}),
("RENASCENCA",{"entities":[(0,10,'EDITORA')]}),
("REVISTA DO OCIDENTE",{"entities":[(0,19,'EDITORA')]}),
("DEL REY GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("UFRN",{"entities":[(0,4,'EDITORA')]}),
("S.E. GRAFIVIT",{"entities":[(0,13,'EDITORA')]}),
("FAROL",{"entities":[(0,5,'EDITORA')]}),
("RIBEIRO GRAFICA",{"entities":[(0,15,'EDITORA')]}),
("GALERA",{"entities":[(0,6,'EDITORA')]}),
("RIO GRAFICA",{"entities":[(0,11,'EDITORA')]}),
("SANGARI",{"entities":[(0,7,'EDITORA')]}),
("RHJ",{"entities":[(0,3,'EDITORA')]}),
("RICORDI BRASILEIRA",{"entities":[(0,18,'EDITORA')]}),
("RIDEEL",{"entities":[(0,6,'EDITORA')]}),
("RIEMMA",{"entities":[(0,6,'EDITORA')]}),
("S.E. SANGARI",{"entities":[(0,12,'EDITORA')]}),
("RIO DE JANEIRO",{"entities":[(0,14,'EDITORA')]}),
("RJ GRAFICA",{"entities":[(0,10,'EDITORA')]}),
("BARCAROLLA",{"entities":[(0,10,'EDITORA')]}),
("CUIABA",{"entities":[(0,6,'EDITORA')]}),
("ALL PRINT",{"entities":[(0,9,'EDITORA')]}),
("RHEMA",{"entities":[(0,5,'EDITORA')]}),
("RIOMAR",{"entities":[(0,6,'EDITORA')]}),
("S.E. MASTER",{"entities":[(0,11,'EDITORA')]}),
("RENASCER",{"entities":[(0,8,'EDITORA')]}),
("RIANI COSTA",{"entities":[(0,11,'EDITORA')]}),
("CORNELSEN",{"entities":[(0,9,'EDITORA')]}),
("RENOIR",{"entities":[(0,6,'EDITORA')]}),
("ROCCO",{"entities":[(0,5,'EDITORA')]}),
("ELETRONICA",{"entities":[(0,10,'EDITORA')]}),
("PROJETO RIO ANIL",{"entities":[(0,16,'EDITORA')]}),
("RESPLENDOR",{"entities":[(0,10,'EDITORA')]}),
("ARCUS",{"entities":[(0,5,'EDITORA')]}),
("RELER",{"entities":[(0,5,'EDITORA')]}),
("ROSARI",{"entities":[(0,6,'EDITORA')]}),
("ROSA DOS TEMPOS",{"entities":[(0,15,'EDITORA')]}),
("S.E. CHRISTUS",{"entities":[(0,13,'EDITORA')]}),
("S.E. ANTARES (ATS)",{"entities":[(0,18,'EDITORA')]}),
("RESTAURO",{"entities":[(0,8,'EDITORA')]}),
("TRES",{"entities":[(0,4,'EDITORA')]}),
("RUA",{"entities":[(0,3,'EDITORA')]}),
("INSTITUTO PLANTARUM",{"entities":[(0,19,'EDITORA')]}),
("REVAN",{"entities":[(0,5,'EDITORA')]}),
("EDITORA SARAIVA",{"entities":[(0,15,'EDITORA')]}),
("SEM INDICACAO",{"entities":[(0,13,'EDITORA')]}),
("SALAMANDRA",{"entities":[(0,10,'EDITORA')]}),
("SABIDA",{"entities":[(0,6,'EDITORA')]}),
("SAE",{"entities":[(0,3,'EDITORA')]}),
("PULSAR EDICOES",{"entities":[(0,14,'EDITORA')]}),
("NOME DA ROSA EDITORA",{"entities":[(0,20,'EDITORA')]}),
("SAS - ARI DE SA",{"entities":[(0,15,'EDITORA')]}),
("SANTILLANA",{"entities":[(0,10,'EDITORA')]}),
("SBB",{"entities":[(0,3,'EDITORA')]}),
("SECAB",{"entities":[(0,5,'EDITORA')]}),
("SABE",{"entities":[(0,4,'EDITORA')]}),
("SABER E LER",{"entities":[(0,11,'EDITORA')]}),
("EDITORA SBN",{"entities":[(0,11,'EDITORA')]}),
("SOC. BRASILEIRA QUIMICA",{"entities":[(0,23,'EDITORA')]}),
("S.E EDUCACIONAL BRASILEIRO",{"entities":[(0,26,'EDITORA')]}),
("SBS",{"entities":[(0,3,'EDITORA')]}),
("SAO BENTO",{"entities":[(0,9,'EDITORA')]}),
("SILVEIRA BUENO",{"entities":[(0,14,'EDITORA')]}),
("SEBO VERMELHO",{"entities":[(0,13,'EDITORA')]}),
("SCIPIONE",{"entities":[(0,8,'EDITORA')]}),
("ESCALA",{"entities":[(0,6,'EDITORA')]}),
("SOC.BIBLIOFILOS BRASIL",{"entities":[(0,22,'EDITORA')]}),
("IDEIA E ACAO",{"entities":[(0,12,'EDITORA')]}),
("S.E. CONQUISTA",{"entities":[(0,14,'EDITORA')]}),
("SCHADE",{"entities":[(0,6,'EDITORA')]}),
("CIA DOS LIVROS",{"entities":[(0,14,'EDITORA')]}),
("SCHOLASTIC",{"entities":[(0,10,'EDITORA')]}),
("SCORTECCI",{"entities":[(0,9,'EDITORA')]}),
("SOFT CRAFT",{"entities":[(0,10,'EDITORA')]}),
("SCHOFIELD E SIMS",{"entities":[(0,16,'EDITORA')]}),
("SERGIPECULTURA",{"entities":[(0,14,'EDITORA')]}),
("SOL E CHUVA",{"entities":[(0,11,'EDITORA')]}),
("S.E. DIDATICO",{"entities":[(0,13,'EDITORA')]}),
("DISAL",{"entities":[(0,5,'EDITORA')]}),
("SONHO DA TRACA",{"entities":[(0,14,'EDITORA')]}),
("S.E. SEI",{"entities":[(0,8,'EDITORA')]}),
("ASSEART",{"entities":[(0,7,'EDITORA')]}),
("SEBRAE",{"entities":[(0,6,'EDITORA')]}),
("SECULT",{"entities":[(0,6,'EDITORA')]}),
("SA EDITORA",{"entities":[(0,10,'EDITORA')]}),
("SEED EDITORIAL",{"entities":[(0,14,'EDITORA')]}),
("SEFER",{"entities":[(0,5,'EDITORA')]}),
("SERMOGRAF",{"entities":[(0,9,'EDITORA')]}),
("S.E. INTEGRAL",{"entities":[(0,13,'EDITORA')]}),
("SELO NEGRO",{"entities":[(0,10,'EDITORA')]}),
("SENAC",{"entities":[(0,5,'EDITORA')]}),
("S.E. PHYSICS",{"entities":[(0,12,'EDITORA')]}),
("EQUIPE - SISTEMA DE ENSINO",{"entities":[(0,26,'EDITORA')]}),
("SERGASA",{"entities":[(0,7,'EDITORA')]}),
("STUDIO SEASONS",{"entities":[(0,14,'EDITORA')]}),
("SETTE LETRAS",{"entities":[(0,12,'EDITORA')]}),
("S.E. UNIFICADO",{"entities":[(0,14,'EDITORA')]}),
("S.E. VICENTINO",{"entities":[(0,14,'EDITORA')]}),
("SEE S.E.",{"entities":[(0,8,'EDITORA')]}),
("SEXTANTE",{"entities":[(0,8,'EDITORA')]}),
("S.E. FARIAS BRITO",{"entities":[(0,17,'EDITORA')]}),
("SOPHOS",{"entities":[(0,6,'EDITORA')]}),
("S.E. FRASE",{"entities":[(0,10,'EDITORA')]}),
("S.E. FUTURO",{"entities":[(0,11,'EDITORA')]}),
("SGEL",{"entities":[(0,4,'EDITORA')]}),
("SUL GRAFICA",{"entities":[(0,11,'EDITORA')]}),
("SALINGER",{"entities":[(0,8,'EDITORA')]}),
("SAGRA LUZZATTO",{"entities":[(0,14,'EDITORA')]}),
("SEGUINTE",{"entities":[(0,8,'EDITORA')]}),
("SHALOM",{"entities":[(0,6,'EDITORA')]}),
("SHINSEN BRASIL",{"entities":[(0,14,'EDITORA')]}),
("SHEDD",{"entities":[(0,5,'EDITORA')]}),
("SHAPE",{"entities":[(0,5,'EDITORA')]}),
("HANSER",{"entities":[(0,6,'EDITORA')]}),
("SICILIANO",{"entities":[(0,9,'EDITORA')]}),
("DISSONARTE EDITORA",{"entities":[(0,18,'EDITORA')]}),
("S.E. SIM",{"entities":[(0,8,'EDITORA')]}),
("SINODAL",{"entities":[(0,7,'EDITORA')]}),
("SALESIANA",{"entities":[(0,9,'EDITORA')]}),
("SILVA",{"entities":[(0,5,'EDITORA')]}),
("SOLAR LEITOR",{"entities":[(0,12,'EDITORA')]}),
("S.E. LOURENCO FILHO",{"entities":[(0,19,'EDITORA')]}),
("S.E. LOGOS",{"entities":[(0,10,'EDITORA')]}),
("SMILE",{"entities":[(0,5,'EDITORA')]}),
("SOL",{"entities":[(0,3,'EDITORA')]}),
("SOLIS",{"entities":[(0,5,'EDITORA')]}),
("EDICOES SM",{"entities":[(0,10,'EDITORA')]}),
("S.E. M3",{"entities":[(0,7,'EDITORA')]}),
("SUMA DE LETRAS",{"entities":[(0,14,'EDITORA')]}),
("SOCIOAMBIENTAL",{"entities":[(0,14,'EDITORA')]}),
("SEMENTE EDITORIAL",{"entities":[(0,17,'EDITORA')]}),
("S.E. SMILE",{"entities":[(0,10,'EDITORA')]}),
("S.E. REDE SANTA MONICA",{"entities":[(0,22,'EDITORA')]}),
("SMITH",{"entities":[(0,5,'EDITORA')]}),
("S.N.*",{"entities":[(0,5,'EDITORA')]}),
("ENSAIO",{"entities":[(0,6,'EDITORA')]}),
("SCHONINGH",{"entities":[(0,9,'EDITORA')]}),
("SINTESE",{"entities":[(0,7,'EDITORA')]}),
("SOLUCAO",{"entities":[(0,7,'EDITORA')]}),
("SOLUCOES CRIATIVAS",{"entities":[(0,18,'EDITORA')]}),
("SOMOS EDUCACAO",{"entities":[(0,14,'EDITORA')]}),
("SONAR",{"entities":[(0,5,'EDITORA')]}),
("PARNASO",{"entities":[(0,7,'EDITORA')]}),
("PENSI - SISTEMA ENSINO",{"entities":[(0,22,'EDITORA')]}),
("S.E. SOPHIA",{"entities":[(0,11,'EDITORA')]}),
("SOPA DE LETRINHAS",{"entities":[(0,17,'EDITORA')]}),
("S.E. POLIEDRO",{"entities":[(0,13,'EDITORA')]}),
("SPRINT",{"entities":[(0,6,'EDITORA')]}),
("S.E. QI",{"entities":[(0,7,'EDITORA')]}),
("SOLAR DO ROSARIO",{"entities":[(0,16,'EDITORA')]}),
("SIMON E SCHUSTER",{"entities":[(0,16,'EDITORA')]}),
("SESI-SP",{"entities":[(0,7,'EDITORA')]}),
("S.E SESI",{"entities":[(0,8,'EDITORA')]}),
("S.E. MONTESSORI",{"entities":[(0,15,'EDITORA')]}),
("RBS PUBLICACOES",{"entities":[(0,15,'EDITORA')]}),
("ASSOESTE",{"entities":[(0,8,'EDITORA')]}),
("SANTUARIO",{"entities":[(0,9,'EDITORA')]}),
("SANTA CLARA",{"entities":[(0,11,'EDITORA')]}),
("SETEMBRO",{"entities":[(0,8,'EDITORA')]}),
("STANDFOR",{"entities":[(0,8,'EDITORA')]}),
("STERLING",{"entities":[(0,8,'EDITORA')]}),
("ARTES GRAFICAS",{"entities":[(0,14,'EDITORA')]}),
("STTIMA",{"entities":[(0,6,'EDITORA')]}),
("SANTA LUZIA",{"entities":[(0,11,'EDITORA')]}),
("SOTESE",{"entities":[(0,6,'EDITORA')]}),
("SANTA RITA",{"entities":[(0,10,'EDITORA')]}),
("STUDIO NOBEL",{"entities":[(0,12,'EDITORA')]}),
("SYSTEMIC",{"entities":[(0,8,'EDITORA')]}),
("SUDAMERICANA DEBOLS",{"entities":[(0,19,'EDITORA')]}),
("SUINARA",{"entities":[(0,7,'EDITORA')]}),
("SULINA",{"entities":[(0,6,'EDITORA')]}),
("SUNDERMANN",{"entities":[(0,10,'EDITORA')]}),
("PRIMUS GRAFICA",{"entities":[(0,14,'EDITORA')]}),
("SUMMUS",{"entities":[(0,6,'EDITORA')]}),
("S.E. VIDA",{"entities":[(0,9,'EDITORA')]}),
("S.E. VISAO",{"entities":[(0,10,'EDITORA')]}),
("S.E. VESPER",{"entities":[(0,11,'EDITORA')]}),
("SCHWARCZ",{"entities":[(0,8,'EDITORA')]}),
("SIX",{"entities":[(0,3,'EDITORA')]}),
("TRAVESSIA",{"entities":[(0,9,'EDITORA')]}),
("BELEM ARTES GRAFICAS",{"entities":[(0,20,'EDITORA')]}),
("TORCULO EDITORIAL",{"entities":[(0,17,'EDITORA')]}),
("TEENAGER",{"entities":[(0,8,'EDITORA')]}),
("ACATU",{"entities":[(0,5,'EDITORA')]}),
("EDITAR",{"entities":[(0,6,'EDITORA')]}),
("TODO LIVRO",{"entities":[(0,10,'EDITORA')]}),
("TORDESILHAS",{"entities":[(0,11,'EDITORA')]}),
("TEMPO BRASILEIRO",{"entities":[(0,16,'EDITORA')]}),
("TECNOPRINT",{"entities":[(0,10,'EDITORA')]}),
("TECNER",{"entities":[(0,6,'EDITORA')]}),
("TERRA",{"entities":[(0,5,'EDITORA')]}),
("ASAS DA ARTE",{"entities":[(0,12,'EDITORA')]}),
("THEX",{"entities":[(0,4,'EDITORA')]}),
("S.E. PENTAGONO (SPAE)",{"entities":[(0,21,'EDITORA')]}),
("TERRENGUI",{"entities":[(0,9,'EDITORA')]}),
("TARGET PREVIEW",{"entities":[(0,14,'EDITORA')]}),
("THESAURUS",{"entities":[(0,9,'EDITORA')]}),
("THOMSON HEINLE",{"entities":[(0,14,'EDITORA')]}),
("ATELIE",{"entities":[(0,6,'EDITORA')]}),
("DIDATICOS",{"entities":[(0,9,'EDITORA')]}),
("TIPO",{"entities":[(0,4,'EDITORA')]}),
("PAULISTA",{"entities":[(0,8,'EDITORA')]}),
("TORA KIDS",{"entities":[(0,9,'EDITORA')]}),
("CELTA",{"entities":[(0,5,'EDITORA')]}),
("LETRAS E EXPRESSOES",{"entities":[(0,19,'EDITORA')]}),
("TRILHA DAS LETRAS",{"entities":[(0,17,'EDITORA')]}),
("ATTEMA",{"entities":[(0,6,'EDITORA')]}),
("METHA EDITORA",{"entities":[(0,13,'EDITORA')]}),
("CONHECIMENTO",{"entities":[(0,12,'EDITORA')]}),
("S.E. TAMANDARE",{"entities":[(0,14,'EDITORA')]}),
("CENTAURO",{"entities":[(0,8,'EDITORA')]}),
("CARNOT",{"entities":[(0,6,'EDITORA')]}),
("TEENS STORIES",{"entities":[(0,13,'EDITORA')]}),
("TANTA TINTA",{"entities":[(0,11,'EDITORA')]}),
("HORIZONTE",{"entities":[(0,9,'EDITORA')]}),
("SCOTT FORESMAN",{"entities":[(0,14,'EDITORA')]}),
("HOUGHTON",{"entities":[(0,8,'EDITORA')]}),
("THOMAS NELSON",{"entities":[(0,13,'EDITORA')]}),
("TOP BOOK",{"entities":[(0,8,'EDITORA')]}),
("S.E. TOTEM",{"entities":[(0,10,'EDITORA')]}),
("POSTUMA",{"entities":[(0,7,'EDITORA')]}),
("TECNOCOPIAS GRAFICA",{"entities":[(0,19,'EDITORA')]}),
("TROCO E PHOTO",{"entities":[(0,13,'EDITORA')]}),
("PETROPOLIS",{"entities":[(0,10,'EDITORA')]}),
("TETRA PARK",{"entities":[(0,10,'EDITORA')]}),
("S.E. OPET",{"entities":[(0,9,'EDITORA')]}),
("TEMPO PRESENTE",{"entities":[(0,14,'EDITORA')]}),
("OS PURITANOS",{"entities":[(0,12,'EDITORA')]}),
("TROPICAL",{"entities":[(0,8,'EDITORA')]}),
("7 LETRAS",{"entities":[(0,8,'EDITORA')]}),
("TRIBO",{"entities":[(0,5,'EDITORA')]}),
("ALETRIA",{"entities":[(0,7,'EDITORA')]}),
("S.E TRILHAS",{"entities":[(0,11,'EDITORA')]}),
("S.E. LASTRO",{"entities":[(0,11,'EDITORA')]}),
("TURTLEBACK BOOKS",{"entities":[(0,16,'EDITORA')]}),
("S.E. STATUS",{"entities":[(0,11,'EDITORA')]}),
("S.E. FTS",{"entities":[(0,8,'EDITORA')]}),
("DEUTSCHE TASCHENBUCH",{"entities":[(0,20,'EDITORA')]}),
("INTRINSECA",{"entities":[(0,10,'EDITORA')]}),
("TALENTO",{"entities":[(0,7,'EDITORA')]}),
("DASTIN",{"entities":[(0,6,'EDITORA')]}),
("VIA LITTERARUM",{"entities":[(0,14,'EDITORA')]}),
("TUPI",{"entities":[(0,4,'EDITORA')]}),
("TUTORIAR",{"entities":[(0,8,'EDITORA')]}),
("NOVO CONCEITO",{"entities":[(0,13,'EDITORA')]}),
("TWO WAY",{"entities":[(0,7,'EDITORA')]}),
("TEXTO NOVO",{"entities":[(0,10,'EDITORA')]}),
("BOM TEXTO",{"entities":[(0,9,'EDITORA')]}),
("AUTA DE SOUZA",{"entities":[(0,13,'EDITORA')]}),
("EDUCAR",{"entities":[(0,6,'EDITORA')]}),
("UCG",{"entities":[(0,3,'EDITORA')]}),
("USINA DE LETRAS",{"entities":[(0,15,'EDITORA')]}),
("DUNA DUETO",{"entities":[(0,10,'EDITORA')]}),
("UEL",{"entities":[(0,3,'EDITORA')]}),
("UESB",{"entities":[(0,4,'EDITORA')]}),
("UFAL",{"entities":[(0,4,'EDITORA')]}),
("UFC",{"entities":[(0,3,'EDITORA')]}),
("UFG",{"entities":[(0,3,'EDITORA')]}),
("UFMG",{"entities":[(0,4,'EDITORA')]}),
("UFPA",{"entities":[(0,4,'EDITORA')]}),
("UFRGS",{"entities":[(0,5,'EDITORA')]}),
("JAUA",{"entities":[(0,4,'EDITORA')]}),
("ULBRA",{"entities":[(0,5,'EDITORA')]}),
("CASULO",{"entities":[(0,6,'EDITORA')]}),
("ULTIMATO",{"entities":[(0,8,'EDITORA')]}),
("UFMA",{"entities":[(0,4,'EDITORA')]}),
("UNB",{"entities":[(0,3,'EDITORA')]}),
("UNIAO CRISTA",{"entities":[(0,12,'EDITORA')]}),
("UNI DUNI",{"entities":[(0,8,'EDITORA')]}),
("UNESCO",{"entities":[(0,6,'EDITORA')]}),
("UNIVERSAL",{"entities":[(0,9,'EDITORA')]}),
("UNIJUI",{"entities":[(0,6,'EDITORA')]}),
("UNIVERSO DOS LIVROS",{"entities":[(0,19,'EDITORA')]}),
("S.E. UNO INTERNACIONAL",{"entities":[(0,22,'EDITORA')]}),
("UNITED PRESS",{"entities":[(0,12,'EDITORA')]}),
("UNESP",{"entities":[(0,5,'EDITORA')]}),
("UNISANTA",{"entities":[(0,8,'EDITORA')]}),
("UNIVERSITARIA",{"entities":[(0,13,'EDITORA')]}),
("UFPB",{"entities":[(0,4,'EDITORA')]}),
("UPF EDITORA",{"entities":[(0,11,'EDITORA')]}),
("AQUARELA",{"entities":[(0,8,'EDITORA')]}),
("UFRJ",{"entities":[(0,4,'EDITORA')]}),
("MUSA",{"entities":[(0,4,'EDITORA')]}),
("USBORNE",{"entities":[(0,7,'EDITORA')]}),
("UFSC",{"entities":[(0,4,'EDITORA')]}),
("S.E. UNINTER",{"entities":[(0,12,'EDITORA')]}),
("UVA",{"entities":[(0,3,'EDITORA')]}),
("UNIVERSIDADE DA FAMILIA",{"entities":[(0,23,'EDITORA')]}),
("VOZES",{"entities":[(0,5,'EDITORA')]}),
("VALCAN",{"entities":[(0,6,'EDITORA')]}),
("VALER",{"entities":[(0,5,'EDITORA')]}),
("NOVA PROSA",{"entities":[(0,10,'EDITORA')]}),
("VERBO",{"entities":[(0,5,'EDITORA')]}),
("VERBUM",{"entities":[(0,6,'EDITORA')]}),
("S.E. CAVE",{"entities":[(0,9,'EDITORA')]}),
("CENTRAL DOS LIVROS",{"entities":[(0,18,'EDITORA')]}),
("VIDA",{"entities":[(0,4,'EDITORA')]}),
("VIDA E CONSCIENCIA",{"entities":[(0,18,'EDITORA')]}),
("VERBO DIVINO",{"entities":[(0,12,'EDITORA')]}),
("VEREDAS",{"entities":[(0,7,'EDITORA')]}),
("VIEIRA",{"entities":[(0,6,'EDITORA')]}),
("VALENCA",{"entities":[(0,7,'EDITORA')]}),
("VERTENTE",{"entities":[(0,8,'EDITORA')]}),
("FIVESTAR",{"entities":[(0,8,'EDITORA')]}),
("VIRGILIA",{"entities":[(0,8,'EDITORA')]}),
("S.E. GERACAO",{"entities":[(0,12,'EDITORA')]}),
("VIA LEITURA",{"entities":[(0,11,'EDITORA')]}),
("VICENS VIVES",{"entities":[(0,12,'EDITORA')]}),
("VIENA",{"entities":[(0,5,'EDITORA')]}),
("VILLA RICA",{"entities":[(0,10,'EDITORA')]}),
("VICENTINA GRAFICA",{"entities":[(0,17,'EDITORA')]}),
("V&R",{"entities":[(0,3,'EDITORA')]}),
("VIRTUAL BOOKS",{"entities":[(0,13,'EDITORA')]}),
("VIT",{"entities":[(0,3,'EDITORA')]}),
("VIA LETTERA",{"entities":[(0,11,'EDITORA')]}),
("S.E. VLE",{"entities":[(0,8,'EDITORA')]}),
("VOULER",{"entities":[(0,6,'EDITORA')]}),
("MEMVAVMEM",{"entities":[(0,9,'EDITORA')]}),
("VOLTA E MEIA",{"entities":[(0,12,'EDITORA')]}),
("PAVIO",{"entities":[(0,5,'EDITORA')]}),
("POLI VARIEDADE",{"entities":[(0,14,'EDITORA')]}),
("S.E. VESPER",{"entities":[(0,11,'EDITORA')]}),
("VERUS",{"entities":[(0,5,'EDITORA')]}),
("VERGARA",{"entities":[(0,7,'EDITORA')]}),
("VIEIRA & LENT",{"entities":[(0,13,'EDITORA')]}),
("VERTICE",{"entities":[(0,7,'EDITORA')]}),
("VERSAL EDITORES",{"entities":[(0,15,'EDITORA')]}),
("MATVEST",{"entities":[(0,7,'EDITORA')]}),
("VITORIA",{"entities":[(0,7,'EDITORA')]}),
("VENTO LESTE",{"entities":[(0,11,'EDITORA')]}),
("VESTCON",{"entities":[(0,7,'EDITORA')]}),
("UNIVERSIDADE",{"entities":[(0,12,'EDITORA')]}),
("VIVEIROS VASCONCELOS",{"entities":[(0,20,'EDITORA')]}),
("VIDA NOVA",{"entities":[(0,9,'EDITORA')]}),
("INSTITUTO SALVADOR DALI",{"entities":[(0,23,'EDITORA')]}),
("S.E. MVI",{"entities":[(0,8,'EDITORA')]}),
("VOX DEI",{"entities":[(0,7,'EDITORA')]}),
("OUTRAS EDITORAS",{"entities":[(0,15,'EDITORA')]}),
("WB EDITORA",{"entities":[(0,10,'EDITORA')]}),
("S.E. WALDORF",{"entities":[(0,12,'EDITORA')]}),
("W EDITORA",{"entities":[(0,9,'EDITORA')]}),
("WILSON & LAFLEUR",{"entities":[(0,16,'EDITORA')]}),
("PREVIEW",{"entities":[(0,7,'EDITORA')]}),
("WS EDITOR",{"entities":[(0,9,'EDITORA')]}),
("S.E.SISTEMA DE ENSINO W",{"entities":[(0,23,'EDITORA')]}),
("WESTERMANN",{"entities":[(0,10,'EDITORA')]}),
("S.E. WILVESTE",{"entities":[(0,13,'EDITORA')]}),
("S.E. HANNAH",{"entities":[(0,11,'EDITORA')]}),
("W11 EDITORES",{"entities":[(0,12,'EDITORA')]}),
("DOM QUIXOTE PUBLICACOES",{"entities":[(0,23,'EDITORA')]}),
("LIVRE EXPRESSAO",{"entities":[(0,15,'EDITORA')]}),
("PAX EDITORA",{"entities":[(0,11,'EDITORA')]}),
("SIGILO XXI",{"entities":[(0,10,'EDITORA')]}),
("XYZ",{"entities":[(0,3,'EDITORA')]}),
("YEARLING",{"entities":[(0,8,'EDITORA')]}),
("YOYO BOOKS",{"entities":[(0,10,'EDITORA')]}),
("YAZIGI",{"entities":[(0,6,'EDITORA')]}),
("Z3 EDITORA",{"entities":[(0,10,'EDITORA')]}),
("JORGE ZAHAR",{"entities":[(0,11,'EDITORA')]}),
("ZEUS",{"entities":[(0,4,'EDITORA')]}),
("ZAHAR",{"entities":[(0,5,'EDITORA')]}),
("METZLER",{"entities":[(0,7,'EDITORA')]}),
("ZOUK",{"entities":[(0,4,'EDITORA')]}),
("PRAZER DE LER",{"entities":[(0,13,'EDITORA')]}),
("ZAPT",{"entities":[(0,4,'EDITORA')]}),
("PANNARTZ",{"entities":[(0,8,'EDITORA')]}),
("ZIT",{"entities":[(0,3,'EDITORA')]}),
("ZASTRAS",{"entities":[(0,7,'EDITORA')]}),
("ALIANZA",{"entities":[(0,7,'EDITORA')]}),
("IBEP - FTD",{"entities":[(0,10,'EDITORA')]}),
("ZOUGLEE",{"entities":[(0,7,'EDITORA')]}),
("EDITORA EDUCACIONAL",{"entities":[(0,19,'EDITORA')]}),
("GEEKIE ONE",{"entities":[(0,10,'EDITORA')]}),
("JC EDITORA",{"entities":[(0,10,'EDITORA')]}),
("TWICE",{"entities":[(0,5,'EDITORA')]}),
("VIA MAKER EDUCATION",{"entities":[(0,19,'EDITORA')]}),
("WALDORF",{"entities":[(0,7,'EDITORA')]}),
("INTERNATIONAL SCHOOL",{"entities":[(0,20,'EDITORA')]}),
("LUNNA",{"entities":[(0,5,'EDITORA')]}),
("BRASIL SABENDO",{"entities":[(0,14,'EDITORA')]}),
("S.E VIVENCIONISTA",{"entities":[(0,17,'EDITORA')]}),
("S.E CONEXIA",{"entities":[(0,11,'EDITORA')]}),
("S.E MASTER",{"entities":[(0,10,'EDITORA')]}),
("S.E MAPLE BEAR",{"entities":[(0,14,'EDITORA')]}),
("SISTEMA DE ENSINO IDEIA",{"entities":[(0,23,'EDITORA')]}),
("EDITORA DA VILA",{"entities":[(0,15,'EDITORA')]}),
("KAIROS",{"entities":[(0,6,'EDITORA')]}),
("OFICINA DAS FINANÇAS - FTD",{"entities":[(0,26,'EDITORA')]}),
("PROGRAMA COMPASSO",{"entities":[(0,17,'EDITORA')]}),
("COGNA",{"entities":[(0,5,'EDITORA')]})
]
