TRAIN_DATA_DISCIPLINA_1E = [
("ADMINISTRACAO",{"entities":[(0,13,'DISCIPLINA')]}),
("ALEMAO",{"entities":[(0,6,'DISCIPLINA')]}),
("Alfabetizacao Matematica",{"entities":[(0,24,'DISCIPLINA')]}),
("ARTE",{"entities":[(0,4,'DISCIPLINA')]}),
("Biologia",{"entities":[(0,8,'DISCIPLINA')]}),
("BIOLOGIA",{"entities":[(0,8,'DISCIPLINA')]}),
("CALIGRAFIA",{"entities":[(0,10,'DISCIPLINA')]}),
("Ciencias",{"entities":[(0,8,'DISCIPLINA')]}),
("CIENCIAS",{"entities":[(0,8,'DISCIPLINA')]}),
("Ciências",{"entities":[(0,8,'DISCIPLINA')]}),
("CIÊNCIAS",{"entities":[(0,8,'DISCIPLINA')]}),
("CONTABILIDADE",{"entities":[(0,13,'DISCIPLINA')]}),
("EDUCACAO FISICA",{"entities":[(0,15,'DISCIPLINA')]}),
("EMPREENDEDORISMO",{"entities":[(0,16,'DISCIPLINA')]}),
("ENSINO RELIGIOSO",{"entities":[(0,16,'DISCIPLINA')]}),
("Espanhol",{"entities":[(0,8,'DISCIPLINA')]}),
("ESPANHOL",{"entities":[(0,8,'DISCIPLINA')]}),
("Filosofia",{"entities":[(0,9,'DISCIPLINA')]}),
("FILOSOFIA",{"entities":[(0,9,'DISCIPLINA')]}),
("Fisica",{"entities":[(0,6,'DISCIPLINA')]}),
("FISICA",{"entities":[(0,6,'DISCIPLINA')]}),
("FRANCES",{"entities":[(0,7,'DISCIPLINA')]}),
("Geografia",{"entities":[(0,9,'DISCIPLINA')]}),
("GEOGRAFIA",{"entities":[(0,9,'DISCIPLINA')]}),
("Geografia Regional",{"entities":[(0,18,'DISCIPLINA')]}),
("GRAMATICA",{"entities":[(0,9,'DISCIPLINA')]}),
("Historia",{"entities":[(0,8,'DISCIPLINA')]}),
("HISTORIA",{"entities":[(0,8,'DISCIPLINA')]}),
("História",{"entities":[(0,8,'DISCIPLINA')]}),
("Historia Regional",{"entities":[(0,17,'DISCIPLINA')]}),
("INFORMATICA",{"entities":[(0,11,'DISCIPLINA')]}),
("Ingles",{"entities":[(0,6,'DISCIPLINA')]}),
("INGLES",{"entities":[(0,6,'DISCIPLINA')]}),
("INTERDISCIPLINAR",{"entities":[(0,16,'DISCIPLINA')]}),
("ITALIANO",{"entities":[(0,8,'DISCIPLINA')]}),
("Letramento e Alfabetizacao",{"entities":[(0,26,'DISCIPLINA')]}),
("Lingua Portuguesa",{"entities":[(0,17,'DISCIPLINA')]}),
("LINGUA PORTUGUESA",{"entities":[(0,17,'DISCIPLINA')]}),
("LITERATURA",{"entities":[(0,10,'DISCIPLINA')]}),
("Matematica",{"entities":[(0,10,'DISCIPLINA')]}),
("MATEMATICA",{"entities":[(0,10,'DISCIPLINA')]}),
("MULTIDISCIPLINAR",{"entities":[(0,16,'DISCIPLINA')]}),
("NATUREZA E SOCIEDADE",{"entities":[(0,20,'DISCIPLINA')]}),
("PEDAGOGIA",{"entities":[(0,9,'DISCIPLINA')]}),
("PORTUGUES",{"entities":[(0,9,'DISCIPLINA')]}),
("PRODUCAO DE TEXTO",{"entities":[(0,17,'DISCIPLINA')]}),
("PSICOLOGIA",{"entities":[(0,10,'DISCIPLINA')]}),
("Quimica",{"entities":[(0,7,'DISCIPLINA')]}),
("QUIMICA",{"entities":[(0,7,'DISCIPLINA')]}),
("REDAÇÃO",{"entities":[(0,7,'DISCIPLINA')]}),
("REDACAO",{"entities":[(0,7,'DISCIPLINA')]}),
("RELIGIAO",{"entities":[(0,8,'DISCIPLINA')]}),
("Sociologia",{"entities":[(0,10,'DISCIPLINA')]}),
("SOCIOLOGIA",{"entities":[(0,10,'DISCIPLINA')]}),
]
